<ToggleButton>
    size_hint: 0.25,1
    state: 'normal'
    background_normal: 'images/deep_orange.png'
    background_down: 'images/press_orange.png'
    group: 'button'
    allow_no_selection: False

<Results>:
    name: 'res_sc'

    ############ Overall Title ######################
    BoxLayout:
        orientation: 'vertical'
        size_hint: 1,1
        MDGridLayout:
            cols:4
            size_hint_y: 0.08
            md_bg_color:0.18,0.18,0.18,1

            MDBoxLayout:
                size_hint:0.15,1
                MDIconButton:
                    id:info_button
                    user_font_size:dp(30)
                    icon:'menu'
                    pos:self.parent.pos
                    size:self.parent.size
                    theme_text_color: 'Custom'
                    text_color: 1,1,1,1
                    on_release: root.nav_drawer.set_state('open')

            MDFloatLayout:
                size_hint: 0.17,1
                orientation: 'horizontal'
                canvas:
                    Color:
                        rgba: 1,1,1,1
                    Line:
                        width: dp(1)
                        points: [self.x+self.width-dp(10),self.y+dp(10),self.x+self.width-dp(10),self.y+self.height-dp(10)]
                Image:
                    source: 'images/logos/icon_orange4.png'
                    size_hint:0.8,0.8
                    pos_hint: {'x':-0.08,'y':0.1}

            MDBoxLayout:
                size_hint: 0.68,1
                Label:
                    size_hint: 1,1
                    text: 'VTA-APP'
                    color: [1,1,1,1]
                    font_name: 'fonts/BlackHanSans-Regular.ttf'
                    text_size: self.parent.size
                    halign: 'left'
                    valign: 'middle'
                    font_size: dp(28)


        MDGridLayout:
            cols:4
            size_hint_y: 0.06
            ToggleButton:
                text: 'Hub'
                id: hub_toggle
                state: 'down' if (root.tc_namemText == 'Turbine Middle' or root.tc_namemText == 'Compressor Middle') else 'normal'
                on_press:
                    sv_results_x.scroll_x = 0
                    sv_hub.scroll_y = 1

            ToggleButton:
                text: 'Mid'
                on_press:
                    sv_results_x.scroll_x = 0.3333333
                    sv_mid.scroll_y = 1
            ToggleButton:
                text: 'Tip'
                on_press:
                    sv_results_x.scroll_x = 0.6666666
                    sv_tip.scroll_y = 1

            ToggleButton:
                text: 'Comp'
                on_press:
                    sv_results_x.scroll_x = 1
                    sv_comp.scroll_y = 1

        ##### Buttons ####
        ScrollView:
            size_hint: 1,0.86
            id: sv_results_x
            do_scroll_x: True
            do_scroll_y: False
            MDGridLayout:
                cols:4
                size_hint:4,1
    #            anim_duration: 0.4
    #            background_color: [1,0.4,0,0.8]

                ScrollView:
                    size: root.height, root.width
                    size_hint: 1,0.25
                    scroll_wheel_distance: '150dp'
                    effect_cls: 'ScrollEffect'
                    id: sv_hub

                    GridLayout:
                        size_hint_y: 1.88
                        rows: 7
                        ############# Image Box ##############
                        FloatLayout:
                            size_hint_y: 0.4
                            canvas:
                                Color:
                                    rgba: 1,1,1,1
                                Rectangle:
                                    source: "images/new_images/comp_hub.png" if root.tc_namemText == 'Compressor Middle' else "images/new_images/turb_hub.png"
                                    size: self.width ,self.height
                                    pos: self.x ,self.y

                        #################################################### Hub Velocity Triangles ############################################################################
                        MDBoxLayout:
                            size_hint_y: 0.08
                            md_bg_color: 1,0.55,0,0.8
                            Label:
                                padding: dp(10),dp(0)
                                text: 'Hub Velocity Triangles'
                                font_size: dp(20)
                                bold: True
                                underline: True
                                text_size: self.size
                                halign:'left'
                                valign: 'middle'

                        GridLayout:
                            cols:2
                            size_hint_y: 0.67
                            canvas:
                                Color:
                                    rgba: 0,0,0,1
                                Line:
                                    width: dp(1)
                                    points: (self.x+self.width/2+dp(2),self.y,self.x+self.width/2+dp(2),self.y+0.88*self.height)
                ###############   Grid gia diaxorismo titlou apo ta apotelesmata #######################
                            GridLayout:
                                rows:2
                                size_hint_x:0.5

                ##################################   Titlos    ####################################
                                BoxLayout:
                                    size_hint_y:0.12
                                    Label:
                                        text:'Coefficients and Angles'
                                        font_size: dp(16)
                                        bold:True
                                        underline: True
                                        text_size: self.size
                                        halign: 'center'
                                        valign: 'middle'

                ################   Grid apotelespata aristera    ###########################
                                GridLayout:
                                    cols:3

                                    GridLayout:
                                        rows:10
                                        size_hint_x:0.67
                                        Label:
                                            font_size:dp(11)
                                            text:"Loading Coefficient \u03C8 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:"Flow Coefficient \u03C61 : " if root.tc_namemText == 'Compressor Middle' else "Flow Coefficient \u03C63 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:"Flow Coefficient \u03C62 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:"Reaction Coefficient Rn : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:"Inlet absolute angle \u03B11 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:"Exit absolute angle \u03B12 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:"Inlet absolute angle \u03B13 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:"Inlet relative angle \u03B21 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:"Exit relative angle \u03B22 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:"Inlet relative angle \u03B23 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                    GridLayout:
                                        rows:10
                                        size_hint_x:0.22
                                        Label:
                                            text: root.phText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.fh1Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.fh2Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.rnhText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.a1hText if root.tc_namemText == 'Compressor Middle' else '------'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.a2hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text:'------' if root.tc_namemText == 'Compressor Middle' else root.a1hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.b1hText if root.tc_namemText == 'Compressor Middle' else '------'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.b2hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            #text: root.b3Text
                                            text:'------' if root.tc_namemText == 'Compressor Middle' else root.b1hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'

                                    GridLayout:
                                        rows:10
                                        size_hint_x:0.11
                                        Label:
                                            text: '[ - ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ - ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ - ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ - ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            #text: root.b3Text
                                            text:'[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'

                ############ Deksi grid to opoio diaxorizei ton titlo apo ta deksio apotelesmata ####################
                            GridLayout:
                                rows:2
                                size_hint_x:0.5
                ##################  Titlos ###############################
                                BoxLayout:
                                    size_hint_y:0.12
                                    Label:
                                        text:'Dimensional Velocities'
                                        font_size: dp(16)
                                        bold:True
                                        underline: True
                                        text_size: self.size
                                        halign: 'center'
                                        valign: 'middle'

                ################   Grid apotelespatvn deksia   ########################
                                GridLayout:
                                    cols:3
                                    GridLayout:
                                        rows:12
                                        size_hint_x:0.55

                                        Label:
                                            font_size:dp(11)
                                            text:' Hub rotational \n speed Uh   '
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Axial Velocity at \n stage 1 Vx1 " if root.tc_namemText == 'Compressor Middle' else " Axial Velocity at \n stage 3 Vx3 "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Axial Velocity at \n stage 2 Vx2 "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:(" Inlet relative \n velocity V1   " if root.tc_namemText == 'Compressor Middle' else " Exit relative \n velocity V3   ")
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Exit absolute \n velocity V2   "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:(" Inlet relative \n velocity W1   "if root.tc_namemText == 'Compressor Middle' else " Exit relative \n velocity W3   ")
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Exit relative \n velocity W2   "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:(" Absolute rotary \n velocity V\u03B81   " if root.tc_namemText == 'Compressor Middle' else " Absolute rotary \n velocity V\u03B83   ")
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Absolute rotary \n velocity V\u03B82  "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:(" Relative rotary \n velocity W\u03B81   " if root.tc_namemText == 'Compressor Middle' else " Relative rotary \n velocity W\u03B83   ")
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Absolute rotary \n velocity W\u03B82  "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Difference of rotary \n velocity DV\u03B8   "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                    GridLayout:
                                        rows:12
                                        size_hint_x:0.25
                                        Label:
                                            text: root.UhText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Vx1hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Vx2hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.V1hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            #text: root.a1Text if slider0.value == 0 else '------'
                                            text: root.V2hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.W1hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.W2hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Vth1hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Vth2hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Wth1hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Wth2hText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.DVthhText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'

                                    GridLayout:
                                        rows:12
                                        size_hint_x:0.2
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text:'[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text:'[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            #text: root.b3Text
                                            text:'[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                        FloatLayout:
                            size_hint_y: 0.45
                            canvas:
                ################ Drawing Area for the triangles  ##########################
                                Color:
                                    rgba:0,0,0,1
                                Line:
                                    width: dp(1.)
                                    rectangle: (self.x + dp(20), self.y + dp(20), self.width - dp(40), self.height - dp(40))

                ###################    Color of the Lines    ##################
                                Color:
                                    rgba:0,0,0,1
                ###################    Uh line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0hText),self.y + float(root.y0Text),float(root.x1hText),self.y + float(root.y1Text))


                ###################    V1h Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0hText),self.y +float(root.y0Text),float(root.xRhText),self.y +float(root.yRhText))

                ###################    W1h Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x1hText),self.y + float(root.y1Text),float(root.xRhText),self.y + float(root.yRhText))

                ###################    W2h Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x1hText),self.y + float(root.y1Text),float(root.xLhText),self.y + float(root.yLhText))

                ###################    V2h Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0hText),self.y + float(root.y0Text),float(root.xLhText),self.y + float(root.yLhText))



                ########### Lines, Dash lines and Labels ###################
                ###################    U dashLine    ##########################
                                Line:
                                    width: dp(1)
                                    points: (float(root.x0hText),self.y + float(root.y0Text)-dp(20),float(root.x1hText),self.y + float(root.y1Text)-dp(20))

                ###################    U Dash lines    ##########################
                                Line:
                                    width: dp(1)
                                    points: (float(root.x0hText),self.y + float(root.y0Text),float(root.x0hText),self.y + float(root.y0Text)-dp(30))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)
                                Line:
                                    width: dp(1)
                                    points: (float(root.x1hText),self.y + float(root.y0Text),float(root.x1hText),self.y + float(root.y0Text)-dp(30))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                                ###################    Vx1 Line    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.x0hText) - dp(20),self.y + float(root.y0Text),float(root.x0hText) - dp(20),self.y + float(root.yLhText))\
                                        if float(root.xLhText) > float(root.x0hText) else\
                                        (float(root.xLhText)- dp(20),self.y + float(root.y0Text),float(root.xLhText) - dp(20),self.y + float(root.yLhText))

                ###################    Vx1 Dash lines    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.x0hText),self.y + float(root.y0Text),float(root.x0hText) - dp(30),self.y + float(root.y0Text))\
                                        if float(root.xLhText) > float(root.x0hText) else\
                                        (float(root.x0hText),self.y + float(root.y0Text),float(root.xLhText) - dp(30) ,self.y + float(root.y0Text))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.xLhText),self.y + float(root.yLhText),float(root.x0hText) - dp(30),self.y + float(root.yLhText))\
                                        if float(root.xLhText) > float(root.x0hText)  else\
                                        (float(root.xLhText),self.y + float(root.yLhText),float(root.xLhText) - dp(30),self.y + float(root.yLhText))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                ###################    Vx Line    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.x1hText) + dp(20),self.y + float(root.y0Text),float(root.x1hText) + dp(20),self.y + float(root.yRhText))\
                                        if float(root.xRhText) < float(root.x1hText) else\
                                        (float(root.xRhText)+ dp(20),self.y + float(root.y0Text),float(root.xRhText)+ dp(20),self.y + float(root.yRhText))

                ###################    Vx Dash lines    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.x1hText),self.y + float(root.y1Text),float(root.x1hText) + dp(30),self.y + float(root.y0Text))\
                                        if float(root.xRhText) < float(root.x1hText) else\
                                        (float(root.x1hText),self.y + float(root.y0Text),float(root.xRhText) + dp(30) ,self.y + float(root.y1Text))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.xRhText),self.y + float(root.yRhText),float(root.x1hText) + dp(30),self.y + float(root.yRhText))\
                                        if float(root.xRhText) < float(root.x1hText)  else\
                                        (float(root.xRhText),self.y + float(root.yRhText),float(root.xRhText)+dp(30),self.y + float(root.yRhText))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                ###################   ΔVθ   Line    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.xLhText),self.y + float(root.yLhText) + dp(20),float(root.xRhText),self.y + float(root.yLhText) + dp(20))\
                                        if float(root.yLhText)>float(root.yRhText) else\
                                        (float(root.xLhText),self.y + float(root.yRhText) + dp(20),float(root.xRhText),self.y + float(root.yRhText) + dp(20))
                ###################    ΔVθ  Dash lines    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.xLhText),self.y + float(root.yLhText),float(root.xLhText),self.y + float(root.yLhText)+dp(30))\
                                        if float(root.yLhText)>float(root.yRhText) else\
                                        (float(root.xLhText),self.y + float(root.yLhText),float(root.xLhText),self.y + float(root.yRhText)+dp(30))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.xRhText),self.y + float(root.yRhText),float(root.xRhText),self.y + float(root.yLhText)+dp(30))\
                                        if float(root.yLhText)>float(root.yRhText) else\
                                        (float(root.xRhText),self.y + float(root.yRhText),float(root.xRhText),self.y + float(root.yRhText)+dp(30))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                ################### Circles of stages numbers ###############################
                                Line:
                                    width: dp(1.)
                                    circle:
                                        (float(root.xLhText) - dp(15),self.y + float(root.yLhText) + dp(17),dp(10))\
                                        if float(root.yLhText) > float(root.yRhText) else\
                                        (float(root.xLhText) - dp(15),self.y + float(root.yRhText) + dp(17),dp(10))

                                Line:
                                    width: dp(1.)
                                    circle:
                                        (float(root.xRhText) + dp(15),self.y + float(root.yLhText) + dp(17),dp(10))\
                                        if float(root.yLhText) > float(root.yRhText) else\
                                        (float(root.xRhText) + dp(15),self.y + float(root.yRhText) + dp(17),dp(10))

                             ################################  Arrows   ##########################################
                ################### Base Velocity Arrows   ##########################
                                ############## U Arrow ###################
                                Color:
                                    rgba: (1,1,1,0) if float(root.x1hText) - float(root.x0hText) < 30 else (0,0,0,1)
                                Triangle:
                                    points:float(root.x0hText),self.y + float(root.y0Text),float(root.x0hText)+dp(25),self.y + float(root.y0Text)+dp(5),float(root.x0hText)+dp(25),self.y + float(root.y0Text)-dp(5)

                                ############## The other 4 Arrows #############
                                Color:
                                    rgba: (0,0,0,1)
                                Triangle:
                                    points:float(root.x0hText),self.y + float(root.y0Text),float(root.xL1uhText),self.y + float(root.yL1uhText),float(root.xL1dhText),self.y + float(root.yL1dhText)

                                Triangle:
                                    points:float(root.x0hText),self.y + float(root.y0Text),float(root.xL2uhText),self.y + float(root.yL2uhText),float(root.xL2dhText),self.y + float(root.yL2dhText)

                                Triangle:
                                    points:float(root.x1hText),self.y + float(root.y1Text),float(root.xR1uhText),self.y + float(root.yR1uhText),float(root.xR1dhText),self.y + float(root.yR1dhText)

                                Triangle:
                                    points:float(root.x1hText),self.y + float(root.y1Text),float(root.xR2uhText),self.y + float(root.yR2uhText),float(root.xR2dhText),self.y + float(root.yR2dhText)

                ##################  U Line Arrows  ####################
                                Color:
                                    rgba: (1,1,1,0) if float(root.x1hText) - float(root.x0hText) < 40 else (0,0,0,1)
                                Triangle:
                                    points:
                                        float(root.x0hText),self.y + float(root.y0Text)-dp(20),float(root.x0hText)+dp(20),\
                                        self.y + float(root.y0Text)-dp(20)+dp(3),float(root.x0hText)+dp(20),self.y + float(root.y0Text)-dp(20)-dp(3)
                                Triangle:
                                    points:
                                        float(root.x1hText),self.y + float(root.y1Text)-dp(20),float(root.x1hText)-dp(20),\
                                        self.y + float(root.y1Text)-dp(20)+dp(3),float(root.x1hText)-dp(20),self.y + float(root.y1Text)-dp(20)-dp(3)

                ##################  ΔVθ Line Arrows  ####################
                                Color:
                                    rgba: (1,1,1,0) if float(root.xRhText) - float(root.xLhText) < 25 else (0,0,0,1)
                                Triangle:
                                    points:
                                        ((float(root.xLhText),self.y + float(root.yLhText) + dp(20),float(root.xLhText)+ dp(20),self.y + float(root.yLhText) + dp(20) + dp(3),\
                                        float(root.xLhText)+ dp(20),self.y + float(root.yLhText) + dp(20) - dp(3))\
                                        if root.tc_namemText == 'Compressor Middle' else\
                                        (float(root.xRhText),self.y + float(root.yLhText) + dp(20),float(root.xRhText)- dp(20),self.y + float(root.yLhText) + dp(20) + dp(3),\
                                        float(root.xRhText)- dp(20),self.y + float(root.yLhText) + dp(20) - dp(3)))\
                                        if float(root.yLhText) > float(root.yRhText) else \
                                        ((float(root.xLhText),self.y + float(root.yRhText) + dp(20),float(root.xLhText)+ dp(20),self.y + float(root.yRhText) + dp(20) + dp(3),\
                                        float(root.xLhText)+ dp(20),self.y + float(root.yRhText) + dp(20) - dp(3))\
                                        if root.tc_namemText == 'Compressor Middle' else\
                                        (float(root.xRhText),self.y + float(root.yRhText) + dp(20),float(root.xRhText)- dp(20),self.y + float(root.yRhText) + dp(20) + dp(3),\
                                        float(root.xRhText)- dp(20),self.y + float(root.yRhText) + dp(20) - dp(3)))

                #####################  Vx2 Line Arrows  ####################
                                Color:
                                    rgba: (1,1,1,0) if (float(root.yRhText) - float(root.y1Text)) < 25 else (0,0,0,1)
                                Triangle:
                                    points:
                                        (float(root.x1hText) + dp(20),self.y + float(root.y1Text),float(root.x1hText) + dp(20) + dp(3),\
                                        self.y + float(root.y1Text)+dp(20),float(root.x1hText) + dp(20) - dp(3),self.y + float(root.y1Text)+dp(20))\
                                        if float(root.xRhText) < float(root.x1hText) else\
                                        (float(root.xRhText)+ dp(20),self.y + float(root.y1Text),float(root.xRhText)+ dp(20) + dp(3),\
                                        self.y + float(root.y1Text) + dp(20),float(root.xRhText)+ dp(20) - dp(3),self.y + float(root.y1Text) + dp(20))

                    #####################  Vx1 Line Arrows  ####################
                                Color:
                                    rgba: (1,1,1,0) if (float(root.yLhText) - float(root.y0Text)) < 25 else (0,0,0,1)
                                Triangle:
                                    points:
                                        (float(root.x0hText) - dp(20),self.y + float(root.y0Text),float(root.x0hText) - dp(20) + dp(3),\
                                        self.y + float(root.y1Text) + dp(20),float(root.x0hText) - dp(20) - dp(3),self.y + float(root.y0Text)+dp(20))\
                                        if float(root.xLhText) > float(root.x0hText) else\
                                        (float(root.xLhText) - dp(20),self.y + float(root.y1Text),float(root.xLhText) - dp(20) + dp(3),\
                                        self.y + float(root.y1Text) + dp(20),float(root.xLhText) - dp(20) - dp(3),self.y + float(root.y1Text) + dp(20))

                            Label:
                                text: 'U'
                                pos: self.parent.x, self.parent.y - self.parent.height/2 + float(root.y0Text) - dp(35)

                            Label:
                                text: 'Vx2'
                                pos:
                                    (self.parent.x + float(root.UhpText)/2 + dp(40),\
                                    self.parent.y - self.parent.height/2 + float(root.y0Text)/2 + float(root.yRhText)/2)\
                                    if float(root.xRhText)<float(root.x1hText)\
                                    else\
                                    (self.parent.x -self.parent.width/2 + float(root.xRhText) + dp(40),\
                                    self.parent.y - self.parent.height/2 + float(root.y0Text)/2 + float(root.yRhText)/2)

                            Label:
                                text: 'Vx1' if root.tc_namemText == 'Compressor Middle' else 'Vx3'
                                pos:
                                    (self.parent.x - float(root.UhpText)/2 - dp(40),\
                                    self.parent.y - self.parent.height/2 + float(root.y0Text)/2 + float(root.yLhText)/2)\
                                    if float(root.xLhText)>float(root.x0hText)\
                                    else\
                                    (self.parent.x - self.parent.width/2 + float(root.xLhText) - dp(40),\
                                    self.parent.y - self.parent.height/2 + float(root.y0Text)/2 + float(root.yLhText)/2)

                            Label:
                                text: '\u0394V\u03B8'
                                pos:
                                    (-float(root.UhpText)/2-float(root.x0hText)+float(root.xLhText)+float(root.UhpText)*float(root.phText)/2,\
                                    self.parent.y - self.parent.height/2 + float(root.yLhText) + dp(35))\
                                    if float(root.yLhText) > float(root.yRhText) else\
                                    (-float(root.UhpText)/2-float(root.x0hText)+float(root.xLhText)+float(root.UhpText)*float(root.phText)/2,\
                                    self.parent.y - self.parent.height/2 + float(root.yRhText) + dp(35))

                            Label:
                                text:'1' if root.tc_namemText == 'Compressor Middle' else '3'
                                pos:
                                    (-float(root.UhpText)/2-float(root.x0hText)+float(root.xLhText) - dp(15),\
                                    self.parent.y - self.parent.height/2 + float(root.yLhText) + dp(17))\
                                    if float(root.yLhText) > float(root.yRhText) else\
                                    (-float(root.UhpText)/2-float(root.x0hText)+float(root.xLhText) - dp(15),\
                                    self.parent.y - self.parent.height/2 + float(root.yRhText) + dp(17))

                            Label:
                                text:'2'
                                pos:
                                    (-float(root.UhpText)/2-float(root.x0hText)+float(root.xRhText) + dp(15),\
                                    self.parent.y - self.parent.height/2 + float(root.yLhText) + dp(17))\
                                    if float(root.yLhText) > float(root.yRhText) else\
                                    (-float(root.UhpText)/2-float(root.x0hText)+float(root.xRhText) + dp(15),\
                                    self.parent.y - self.parent.height/2 + float(root.yRhText) + dp(17))

#                            MDLabel:
#                                pos: self.parent.x + dp(23),self.parent.y + self.height/2 - dp(30)
#                                font_style: 'Body1'
#                                text:
#                                    'Hub triangles were ' + (str(round(100*(1-(float(root.UhpText)*float(root.UmText)/(float(root.UhText)*float(root.UText)))),1))) + ' %' + ' scaled down.'\
#                                    if (float(root.UhpText) < (float(root.UhText)/float(root.UmText))*float(root.UText)) else ''
                        GridLayout:
                            cols:2
                            size_hint_y: 0.1
                            BoxLayout:
                                size_hint_x:0.3
                                padding:dp(10)
                                spacing:dp(10)
                                MDRectangleFlatIconButton:
                                    icon:'arrow-left-bold'
                                    md_bg_color:[0.4,.4,.4,1]
                                    text_color: [1,1,1,1]
                                    size_hint:0.25,1
                                    text:"Back"
                                    on_press:
#                                        sv_hub.scroll_y = 1
                                        root.manager.current = "Main"
                                        root.manager.transition.direction = "right"


                            BoxLayout:
                                size_hint_x:0.7
                                MDLabel:
                                    font_size: dp(13)
                                    color: 1,0,0,1
                                    text:
                                        ('*Hub triangles were ' + (str(round(100*(1-float(root.UhpText)/float(root.Uhp_cText)),1))) + ' %' + ' scaled down in order to fit.')\
                                        if (float(root.UhpText)<float(root.Uhp_cText)) else ''
                        MDBoxLayout:
                            orientation: 'vertical'
                            padding: dp(10),dp(0)
                            size_hint: 1,0.135
                            md_bg_color:0.18,0.18,0.18,1
                            canvas:
                                Color:
                                    rgba: 0.8,0.8,0.8,0.5
                                Line:
                                    width: dp(7.5)
                                    points: (self.x,self.height-dp(7.5),self.width,self.height-dp(7.5))
                            Label:
                                text: 'Velocity Triangles Analysis App/Dimensional Analysis/Hub '
                                font_size: dp(14)
                                color: 1,1,1,1
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'

                ScrollView:
                    size: root.height, root.width
                    size_hint: 1,0.25
                    scroll_wheel_distance: '150dp'
                    effect_cls: 'ScrollEffect'
                    id: sv_mid

                    GridLayout:
                        size_hint_y: 1.88
                        rows: 7

                        ############# Image Box ##############
                        FloatLayout:
                            size_hint_y: 0.4
                            canvas:
                                Color:
                                    rgba: 1,1,1,1
                                Rectangle:
                                    source: "images/new_images/comp_mid.png" if root.tc_namemText == 'Compressor Middle' else "images/new_images/turb_mid.png"
                                    size: self.width,self.height
                                    pos: self.x ,self.y
                        MDBoxLayout:
                            size_hint_y: 0.08
                            md_bg_color:1,0.55,0,0.8
                            Label:
                                padding: dp(10),dp(0)
                                text: 'Middle Velocity Triangles'
                                font_size: dp(20)
                                bold: True
                                underline: True
                                text_size: self.size
                                halign:'left'
                                valign: 'middle'

                ######################GRid me ta grapta apotelesmata #############################
                        GridLayout:
                            cols:2
                            size_hint_y: 0.67
                            canvas:
                                Color:
                                    rgba: 0,0,0,1
                                Line:
                                    width: dp(1)
                                    points: (self.x+self.width/2+dp(2),self.y,self.x+self.width/2+dp(2),self.y+0.88*self.height)

                ###############   Grid gia diaxorismo titlou apo ta apotelesmata #######################
                            GridLayout:
                                rows:2
                                size_hint_x:0.5

                ##################################   Titlos    ####################################
                                BoxLayout:
                                    size_hint_y:0.12
                                    Label:
                                        text:'Coefficients and Angles'
                                        font_size: dp(16)
                                        bold:True
                                        underline: True
                                        text_size: self.size
                                        halign: 'center'
                                        valign: 'middle'

                ################   Grid apotelespata aristera    ###########################
                                GridLayout:
                                    cols:3

                                    GridLayout:
                                        rows:9
                                        size_hint_x:0.67

                                        Label:
                                            font_size:dp(11)
                                            text:"Loading Coefficient \u03C8 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Flow Coefficient \u03C6 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Reaction Coefficient Rn : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Inlet absolute angle \u03B11 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Exit absolute angle \u03B12 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Inlet absolute angle \u03B13 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Inlet relative angle \u03B21 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Exit relative angle \u03B22 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Inlet relative angle \u03B23 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'


                                    GridLayout:
                                        rows:9
                                        size_hint_x:0.22

                                        Label:
                                            text: root.pText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        BoxLayout:
                                            size: self.size
                                            canvas:
                                                Color:
                                                    rgba:
                                                        (1,0,0,1) if root.XText == '[3, 5, 7]' or root.XText == '[1, 5, 7]'\
                                                        or root.XText == '[1, 3, 7]' or root.XText == '[1, 3, 5]'\
                                                        or root.XText == '[3, 4, 6]' or root.XText == '[1, 4, 6]'\
                                                        or root.XText == '[1, 3, 6]' or root.XText == '[1, 3, 4]' else (0,0,0,0)
                                                Line:
                                                    width: dp(1.2)
                                                    ellipse: (self.x,self.y + dp(10),self.width ,self.height - dp(20))
                                            Label:
                                                text: root.fText
                                                font_size:dp(11)
                                                text_size: self.size
                                                halign: 'center'
                                                valign: 'middle'
                                        Label:
                                            text: root.rnText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.a1Text if root.tc_namemText == 'Compressor Middle' else '------'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.a2Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text:'------' if root.tc_namemText == 'Compressor Middle' else root.a1Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.b1Text if root.tc_namemText == 'Compressor Middle' else '------'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.b2Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            #text: root.b3Text
                                            text:'------' if root.tc_namemText == 'Compressor Middle' else root.b1Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'

                                    GridLayout:
                                        rows:9
                                        size_hint_x:0.11

                                        Label:
                                            text: '[ - ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ - ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ - ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text:'[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'

                ############ Deksi grid to opoio diaxorizei ton titlo apo ta deksio apotelesmata ####################
                            GridLayout:
                                rows:2
                                size_hint_x:0.5
                ##################  Titlos ###############################
                                BoxLayout:
                                    size_hint_y:0.12
                                    Label:
                                        text:'Dimensional Velocities'
                                        font_size: dp(16)
                                        bold:True
                                        underline: True
                                        text_size: self.size
                                        halign: 'center'
                                        valign: 'middle'

                ################   Grid apotelespatvn deksia   ########################
                                GridLayout:
                                    cols:3

                                    GridLayout:
                                        rows:11
                                        size_hint_x:0.55

                                        Label:
                                            font_size:dp(11)
                                            text:' Middle rotational \n speed Um   '
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'


                                        Label:
                                            font_size:dp(11)
                                            text:" Axial Velocity Vx "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:(" Inlet relative \n velocity V1   "if root.tc_namemText == 'Compressor Middle' else " Exit relative \n velocity V3   ")
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:" Exit absolute \n velocity V2   "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:(" Inlet relative \n velocity W1   "if root.tc_namemText == 'Compressor Middle' else " Exit relative \n velocity W3   ")
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:" Exit relative \n velocity W2   "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:(" Absolute rotary \n velocity V\u03B81   " if root.tc_namemText == 'Compressor Middle' else " Absolute rotary \n velocity V\u03B83   ")
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Absolute rotary \n velocity V\u03B82  "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:(" Relative rotary \n velocity W\u03B81   " if root.tc_namemText == 'Compressor Middle' else " Relative rotary \n velocity W\u03B83   ")
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Absolute rotary \n velocity W\u03B82  "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:" Difference of rotary \n velocity DV\u03B8   "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'


                                    GridLayout:
                                        rows:11
                                        size_hint_x:0.25

                                        Label:
                                            text: root.UmText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'

                                        Label:
                                            text: root.VxText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.V1Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            #text: root.a1Text if slider0.value == 0 else '------'
                                            text: root.V2Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.W1Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.W2Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Vth1Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Vth2Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Wth1Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Wth2Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.DVthText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                    GridLayout:
                                        rows:11
                                        size_hint_x:0.2

                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text:'[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text:'[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            #text: root.b3Text
                                            text:'[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'

                ########Box sthn mesh . Kato apo ta apotelesmata (Ekei pou tha einai ta trigwna) ###########
                        FloatLayout:
                            size_hint_y: 0.45
                            canvas:
                                Color:
                                    rgba:0,0,0,1
                                Line:
                                    width: dp(1.)
                                    rectangle: (self.x + dp(20), self.y + dp(20), self.width - dp(40), self.height - dp(40))

                ###################    Color of the Lines    ##################
                                Color:
                                    rgba:0,0,0,1
                ###################    U line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0Text),self.y + float(root.y0Text),float(root.x1Text),self.y + float(root.y1Text))


                ###################    V1 Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0Text),self.y +float(root.y0Text),float(root.xRText),self.y +float(root.yRText))

                ###################    W1 Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x1Text),self.y + float(root.y1Text),float(root.xRText),self.y + float(root.yRText))

                ###################    W2 Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x1Text),self.y + float(root.y1Text),float(root.xLText),self.y + float(root.yLText))

                ###################    V2 Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0Text),self.y + float(root.y0Text),float(root.xLText),self.y + float(root.yLText))

                ########### Lines, Dash lines and Labels ###################
                ###################    U dashLine    ##########################
                                Line:
                                    width: dp(1)
                                    points: (float(root.x0Text),self.y + float(root.y0Text)-dp(20),float(root.x1Text),self.y + float(root.y1Text)-dp(20))

                ###################    U Dash lines    ##########################
                                Line:
                                    width: dp(1)
                                    points: (float(root.x0Text),self.y + float(root.y0Text),float(root.x0Text),self.y + float(root.y0Text)-dp(30))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)
                                Line:
                                    width: dp(1)
                                    points: (float(root.x1Text),self.y + float(root.y0Text),float(root.x1Text),self.y + float(root.y0Text)-dp(30))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                ###################    Vx Line    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.x1Text) + dp(20),self.y + float(root.y0Text),float(root.x1Text) + dp(20),self.y + float(root.yRText))\
                                        if float(root.xRText) < float(root.x1Text) else\
                                        (float(root.xRText)+ dp(20),self.y + float(root.y0Text),float(root.xRText)+ dp(20),self.y + float(root.yRText))

                ###################    Vx Dash lines    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.x1Text),self.y + float(root.y1Text),float(root.x1Text) + dp(30),self.y + float(root.y0Text))\
                                        if float(root.xRText) < float(root.x1Text) else\
                                        (float(root.x1Text),self.y + float(root.y0Text),float(root.xRText) + dp(30) ,self.y + float(root.y1Text))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.xRText),self.y + float(root.yRText),float(root.x1Text) + dp(30),self.y + float(root.yRText))\
                                        if float(root.xRText) < float(root.x1Text)  else\
                                        (float(root.xRText),self.y + float(root.yRText),float(root.xRText)+dp(30),self.y + float(root.yRText))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                ###################   ΔVθ   Line    ##########################
                                Line:
                                    width: dp(1)
                                    points: (float(root.xLText),self.y + float(root.yLText) + dp(20),float(root.xRText),self.y + float(root.yRText) + dp(20))

                ###################    ΔVθ  Dash lines    ##########################
                                Line:
                                    width: dp(1)
                                    points: (float(root.xLText),self.y + float(root.yLText),float(root.xLText),self.y + float(root.yLText)+dp(30))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)
                                Line:
                                    width: dp(1)
                                    points: (float(root.xRText),self.y + float(root.yRText),float(root.xRText),self.y + float(root.yRText)+dp(30))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                ################### Circles of stages numbers ###############################
                                Line:
                                    width: dp(1.)
                                    circle:
                                        (float(root.xLText) - dp(15),self.y + float(root.yLText) + dp(17),dp(10))

                                Line:
                                    width: dp(1.)
                                    circle:
                                        (float(root.xRText) + dp(15),self.y + float(root.yLText) + dp(17),dp(10))



                             ################################  Arrows   ##########################################
                ################### Base Velocity Arrows   ##########################
                                ################ U Arrow ##############
                                Color:
                                    rgba: (1,1,1,0) if float(root.x1Text) - float(root.x0Text) < 30 else (0,0,0,1)
                                Triangle:
                                    points:float(root.x0Text),self.y + float(root.y0Text),float(root.x0Text)+dp(25),self.y + float(root.y0Text)+dp(5),float(root.x0Text)+dp(25),self.y + float(root.y0Text)-dp(5)

                                ################ The other 4 Base Arrows #################
                                Color:
                                    rgba: (0,0,0,1)
                                Triangle:
                                    points:float(root.x0Text),self.y + float(root.y0Text),float(root.xL1uText),self.y + float(root.yL1uText),float(root.xL1dText),self.y + float(root.yL1dText)

                                Triangle:
                                    points:float(root.x0Text),self.y + float(root.y0Text),float(root.xL2uText),self.y + float(root.yL2uText),float(root.xL2dText),self.y + float(root.yL2dText)

                                Triangle:
                                    points:float(root.x1Text),self.y + float(root.y1Text),float(root.xR1uText),self.y + float(root.yR1uText),float(root.xR1dText),self.y + float(root.yR1dText)

                                Triangle:
                                    points:float(root.x1Text),self.y + float(root.y1Text),float(root.xR2uText),self.y + float(root.yR2uText),float(root.xR2dText),self.y + float(root.yR2dText)

                ##################  U Line Arrows  ####################
                                Color:
                                    rgba: (1,1,1,0) if float(root.x1Text) - float(root.x0Text) < 40 else (0,0,0,1)
                                Triangle:
                                    points:
                                        float(root.x0Text),self.y + float(root.y0Text)-dp(20),float(root.x0Text)+dp(20),\
                                        self.y + float(root.y0Text)-dp(20)+dp(3),float(root.x0Text)+dp(20),self.y + float(root.y0Text)-dp(20)-dp(3)
                                Triangle:
                                    points:
                                        float(root.x1Text),self.y + float(root.y1Text)-dp(20),float(root.x1Text)-dp(20),\
                                        self.y + float(root.y1Text)-dp(20)+dp(3),float(root.x1Text)-dp(20),self.y + float(root.y1Text)-dp(20)-dp(3)

                ##################  ΔVθ Line Arrows  ####################
                                Color:
                                    rgba: (1,1,1,0) if float(root.xRText) - float(root.xLText) < 25 else (0,0,0,1)
                                Triangle:
                                    points:
                                        (float(root.xLText),self.y + float(root.yLText) + dp(20),float(root.xLText)+ dp(20),self.y + float(root.yLText) + dp(20) + dp(3),\
                                        float(root.xLText)+ dp(20),self.y + float(root.yLText) + dp(20) - dp(3)) if root.tc_namemText == 'Compressor Middle' else\
                                        (float(root.xRText),self.y + float(root.yRText) + dp(20),float(root.xRText)- dp(20),self.y + float(root.yRText) + dp(20) + dp(3),\
                                        float(root.xRText)- dp(20),self.y + float(root.yRText) + dp(20) - dp(3))

                #####################  Vx Line Arrows  ####################
                                Color:
                                    rgba: (1,1,1,0) if float(root.yRText) - float(root.y1Text) < 25 else (0,0,0,1)
                                Triangle:
                                    points:
                                        (float(root.x1Text) + dp(20),self.y + float(root.y1Text),float(root.x1Text) + dp(20) + dp(3),\
                                        self.y + float(root.y1Text)+dp(20),float(root.x1Text) + dp(20) - dp(3),self.y + float(root.y1Text)+dp(20))\
                                        if float(root.xRText) < float(root.x1Text) else\
                                        (float(root.xRText)+ dp(20),self.y + float(root.y1Text),float(root.xRText)+ dp(20) + dp(3),\
                                        self.y + float(root.y1Text) + dp(20),float(root.xRText)+ dp(20) - dp(3),self.y + float(root.y1Text) + dp(20))


                            Label:
                                text: 'U'
                                pos: self.parent.x, self.parent.y - self.parent.height/2 + float(root.y0Text) - dp(35)

                            Label:
                                text: 'Vx'
                                pos:
                                    (self.parent.x + float(root.UText)/2 + dp(40),\
                                    self.parent.y - self.parent.height/2  + float(root.y0Text) + float(root.UText)*float(root.fText)/2)\
                                    if float(root.xRText) < float(root.x1Text)\
                                    else\
                                    (self.parent.x - self.parent.width/2 + float(root.xRText) + dp(40),\
                                    self.parent.y - self.parent.height/2  + float(root.y0Text) + float(root.UText)*float(root.fText)/2)

                            Label:
                                text: '\u0394V\u03B8'
                                pos:
                                    -float(root.UText)/2-float(root.x0Text)+float(root.xLText)+float(root.UText)*float(root.pText)/2,\
                                    self.parent.y - self.parent.height/2 + float(root.y0Text) + float(root.UText)*float(root.fText) + dp(35)

                            Label:
                                text:'1' if root.tc_namemText == 'Compressor Middle' else '3'
                                pos:
                                    -float(root.UText)/2-float(root.x0Text)+float(root.xLText) - dp(15),\
                                    self.parent.y - self.parent.height/2 + float(root.y0Text) + float(root.UText)*float(root.fText) + dp(17)

                            Label:
                                text:'2'
                                pos:
                                    -float(root.UText)/2-float(root.x0Text)+float(root.xRText) + dp(15),\
                                    self.parent.y - self.parent.height/2 + float(root.y0Text) + float(root.UText)*float(root.fText) + dp(17)

                        #####################    Button  ####################
                        GridLayout:
                            cols:2
                            size_hint_y: 0.1
                            BoxLayout:
                                size_hint_x:0.3
                                padding:dp(10)
                                spacing:dp(10)
                                MDRectangleFlatIconButton:
                                    icon:'arrow-left-bold'
                                    md_bg_color:[0.4,.4,.4,1]
                                    text_color: [1,1,1,1]
                                    size_hint:0.25,1
                                    text:"Back"
                                    on_press:
#                                        sv_mid.scroll_y = 1
                                        root.manager.current = "Main"
                                        root.manager.transition.direction = "right"


                            BoxLayout:
                                size_hint_x:0.7

                        MDBoxLayout:
                            orientation: 'vertical'
                            padding: dp(10),dp(0)
                            size_hint: 1,0.135
                            md_bg_color:0.18,0.18,0.18,1
                            canvas:
                                Color:
                                    rgba: 0.8,0.8,0.8,0.5
                                Line:
                                    width: dp(7.5)
                                    points: (self.x,self.height-dp(7.5),self.width,self.height-dp(7.5))
                            Label:
                                text: 'Velocity Triangles Analysis App/Dimensional Analysis/Middle '
                                font_size: dp(14)
                                color: 1,1,1,1
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'

                ScrollView:
                    size: root.height, root.width
                    size_hint: 1,0.25
                    scroll_wheel_distance: '150dp'
                    effect_cls: 'ScrollEffect'
                    id: sv_tip

                    GridLayout:
                        size_hint_y: 1.88
                        rows: 7

                        ############# Image Box ##############
                        FloatLayout:
                            size_hint_y: 0.4
                            canvas:
                                Color:
                                    rgba: 1,1,1,1
                                Rectangle:
                                    source: "images/new_images/comp_tip.png" if root.tc_namemText == 'Compressor Middle' else "images/new_images/turb_tip.png"
                                    size: self.width,self.height
                                    pos: self.x,self.y

                        #################################################### Tip Velocity Triangles ############################################################################
                        MDBoxLayout:
                            size_hint_y: 0.08
                            md_bg_color: 1,0.55,0,0.8

                            Label:
                                padding: dp(10),dp(0)
                                text: 'Tip Velocity Triangles'
                                font_size: dp(20)
                                bold: True
                                underline: True
                                text_size: self.size
                                halign:'left'
                                valign: 'middle'

                        GridLayout:
                            cols:2
                            size_hint_y: 0.67
                            canvas:
                                Color:
                                    rgba: 0,0,0,1
                                Line:
                                    width: dp(1)
                                    points: (self.x+self.width/2+dp(2),self.y,self.x+self.width/2+dp(2),self.y+0.88*self.height)

                ###############   Grid gia diaxorismo titlou apo ta apotelesmata #######################
                            GridLayout:
                                rows:2
                                size_hint_x:0.5

                ##################################   Titlos    ####################################
                                BoxLayout:
                                    size_hint_y:0.12

                                    Label:
                                        text:'Coefficients and Angles'
                                        font_size: dp(16)
                                        bold:True
                                        underline: True
                                        text_size: self.size
                                        halign: 'center'
                                        valign: 'middle'

                ################   Grid apotelespata aristera    ###########################
                                GridLayout:
                                    cols:3

                                    GridLayout:
                                        rows:10
                                        size_hint_x:0.67

                                        Label:
                                            font_size:dp(11)
                                            text:"Loading Coefficient \u03C8 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Flow Coefficient \u03C61 : " if root.tc_namemText == 'Compressor Middle' else "Flow Coefficient \u03C63 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Flow Coefficient \u03C62 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Reaction Coefficient Rn : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Inlet absolute angle \u03B11 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Exit absolute angle \u03B12 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Inlet absolute angle \u03B13 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Inlet relative angle \u03B21 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Exit relative angle \u03B22 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'

                                        Label:
                                            font_size:dp(11)
                                            text:"Inlet relative angle \u03B23 : "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'


                                    GridLayout:
                                        rows:10
                                        size_hint_x:0.22

                                        Label:
                                            text: root.ptText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.ft1Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.ft2Text
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.rntText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.a1tText if root.tc_namemText == 'Compressor Middle' else '------'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.a2tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text:'------' if root.tc_namemText == 'Compressor Middle' else root.a1tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.b1tText if root.tc_namemText == 'Compressor Middle' else '------'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.b2tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            #text: root.b3Text
                                            text:'------' if root.tc_namemText == 'Compressor Middle' else root.b1tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'

                                    GridLayout:
                                        rows:10
                                        size_hint_x:0.11

                                        Label:
                                            text: '[ - ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ - ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ - ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ - ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            #text: root.b3Text
                                            text:'[ \u00B0 ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'

                ############ Deksi grid to opoio diaxorizei ton titlo apo ta deksio apotelesmata ####################
                            GridLayout:
                                rows:2
                                size_hint_x:0.5
                ##################  Titlos ###############################
                                BoxLayout:
                                    size_hint_y:0.12

                                    Label:
                                        text:'Dimensional Velocities'
                                        font_size: dp(16)
                                        bold:True
                                        underline: True
                                        text_size: self.size
                                        halign: 'center'
                                        valign: 'middle'

                ################   Grid apotelespatvn deksia   ########################
                                GridLayout:
                                    cols:3

                                    GridLayout:
                                        rows:12
                                        size_hint_x:0.55

                                        Label:
                                            font_size:dp(11)
                                            text:' Tip rotational \n speed Ut   '
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Axial Velocity at \n stage 1 Vx1 " if root.tc_namemText == 'Compressor Middle' else " Axial Velocity at \n stage 3 Vx3 "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Axial Velocity at \n stage 2 Vx2 "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:(" Inlet relative \n velocity V1   "if root.tc_namemText == 'Compressor Middle' else " Exit relative \n velocity V3   ")
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Exit absolute \n velocity V2   "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:(" Inlet relative \n velocity W1   "if root.tc_namemText == 'Compressor Middle' else " Exit relative \n velocity W3   ")
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Exit relative \n velocity W2   "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:(" Absolute rotary \n velocity V\u03B81   " if root.tc_namemText == 'Compressor Middle' else " Absolute rotary \n velocity V\u03B83   ")
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Absolute rotary \n velocity V\u03B82  "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:(" Relative rotary \n velocity W\u03B81   " if root.tc_namemText == 'Compressor Middle' else " Relative rotary \n velocity W\u03B83   ")
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Absolute rotary \n velocity W\u03B82  "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'
                                        Label:
                                            font_size:dp(11)
                                            text:" Difference of rotary \n velocity DV\u03B8   "
                                            text_size: self.size
                                            halign: 'right'
                                            valign: 'middle'


                                    GridLayout:
                                        rows:12
                                        size_hint_x:0.25

                                        Label:
                                            text: root.UtText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Vx1tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Vx2tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.V1tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            #text: root.a1Text if slider0.value == 0 else '------'
                                            text: root.V2tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.W1tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.W2tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Vth1tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Vth2tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Wth1tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.Wth2tText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                        Label:
                                            text: root.DVthtText
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'center'
                                            valign: 'middle'
                                    GridLayout:
                                        rows:12
                                        size_hint_x:0.2

                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text:'[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text:'[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text: '[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                                        Label:
                                            text:'[ m/s ]'
                                            font_size:dp(11)
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'middle'
                        FloatLayout:
                            size_hint_y: 0.45
                            canvas:
                                Color:
                                    rgba:0,0,0,1
                                Line:
                                    width: dp(1.)
                                    rectangle: (self.x + dp(20), self.y + dp(20), self.width - dp(40), self.height - dp(40))

                ###################    Color of the Lines    ##################
                                Color:
                                    rgba:0,0,0,1
                ###################    Ut line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0tText),self.y + float(root.y0Text),float(root.x1tText),self.y + float(root.y1Text))


                ###################    V1t Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0tText),self.y +float(root.y0Text),float(root.xRtText),self.y +float(root.yRtText))

                ###################    W1t Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x1tText),self.y + float(root.y1Text),float(root.xRtText),self.y + float(root.yRtText))

                ###################    W2t Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x1tText),self.y + float(root.y1Text),float(root.xLtText),self.y + float(root.yLtText))

                ###################    V2t Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0tText),self.y + float(root.y0Text),float(root.xLtText),self.y + float(root.yLtText))

                ########### Lines, Dash lines and Labels ###################
                ###################    U dashLine    ##########################
                                Line:
                                    width: dp(1)
                                    points: (float(root.x0tText),self.y + float(root.y0Text)-dp(20),float(root.x1tText),self.y + float(root.y1Text)-dp(20))

                ###################    U Dash lines    ##########################
                                Line:
                                    width: dp(1)
                                    points: (float(root.x0tText),self.y + float(root.y0Text),float(root.x0tText),self.y + float(root.y0Text)-dp(30))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)
                                Line:
                                    width: dp(1)
                                    points: (float(root.x1tText),self.y + float(root.y0Text),float(root.x1tText),self.y + float(root.y0Text)-dp(30))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                                ###################    Vx1 Line    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.x0tText) - dp(20),self.y + float(root.y0Text),float(root.x0tText) - dp(20),self.y + float(root.yLtText))\
                                        if float(root.xLtText) > float(root.x0tText) else\
                                        (float(root.xLtText)- dp(20),self.y + float(root.y0Text),float(root.xLtText) - dp(20),self.y + float(root.yLtText))

                ###################    Vx1 Dash lines    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.x0tText),self.y + float(root.y0Text),float(root.x0tText) - dp(30),self.y + float(root.y0Text))\
                                        if float(root.xLtText) > float(root.x0tText) else\
                                        (float(root.x0tText),self.y + float(root.y0Text),float(root.xLtText) - dp(30) ,self.y + float(root.y0Text))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.xLtText),self.y + float(root.yLtText),float(root.x0tText) - dp(30),self.y + float(root.yLtText))\
                                        if float(root.xLtText) > float(root.x0tText)  else\
                                        (float(root.xLtText),self.y + float(root.yLtText),float(root.xLtText) - dp(30),self.y + float(root.yLtText))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)


                ###################    Vx2 Line    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.x1tText) + dp(20),self.y + float(root.y0Text),float(root.x1tText) + dp(20),self.y + float(root.yRtText))\
                                        if float(root.xRtText) < float(root.x1tText) else\
                                        (float(root.xRtText)+ dp(20),self.y + float(root.y0Text),float(root.xRtText)+ dp(20),self.y + float(root.yRtText))

                ###################    Vx2 Dash lines    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.x1tText),self.y + float(root.y1Text),float(root.x1tText) + dp(30),self.y + float(root.y0Text))\
                                        if float(root.xRtText) < float(root.x1tText) else\
                                        (float(root.x1tText),self.y + float(root.y0Text),float(root.xRtText) + dp(30) ,self.y + float(root.y1Text))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.xRtText),self.y + float(root.yRtText),float(root.x1tText) + dp(30),self.y + float(root.yRtText))\
                                        if float(root.xRtText) < float(root.x1tText)  else\
                                        (float(root.xRtText),self.y + float(root.yRtText),float(root.xRtText)+dp(30),self.y + float(root.yRtText))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                ###################   ΔVθ   Line    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.xLtText),self.y + float(root.yRtText) + dp(20),float(root.xRtText),self.y + float(root.yRtText) + dp(20))\
                                        if float(root.yLtText)<float(root.yRtText) else\
                                        (float(root.xLtText),self.y + float(root.yLtText) + dp(20),float(root.xRtText),self.y + float(root.yLtText) + dp(20))

                ###################    ΔVθ  Dash lines    ##########################
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.xLtText),self.y + float(root.yLtText),float(root.xLtText),self.y + float(root.yRtText)+dp(30))\
                                        if float(root.yLtText)<float(root.yRtText) else\
                                        (float(root.xLtText),self.y + float(root.yLtText),float(root.xLtText),self.y + float(root.yLtText)+dp(30))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)
                                Line:
                                    width: dp(1)
                                    points:
                                        (float(root.xRtText),self.y + float(root.yRtText),float(root.xRtText),self.y + float(root.yRtText)+dp(30))\
                                        if float(root.yLtText)<float(root.yRtText) else\
                                        (float(root.xRtText),self.y + float(root.yRtText),float(root.xRtText),self.y + float(root.yLtText)+dp(30))
                                    dash_length: dp(5)
                                    dash_offset: dp(5)

                ################### Circles of stages numbers ###############################
                                Line:
                                    width: dp(1.)
                                    circle:
                                        (float(root.xLtText) - dp(15),self.y + float(root.yRtText) + dp(17),dp(10))\
                                        if float(root.yRtText) > float(root.yLtText) else\
                                        (float(root.xLtText) - dp(15),self.y + float(root.yLtText) + dp(17),dp(10))

                                Line:
                                    width: dp(1.)
                                    circle:
                                        (float(root.xRtText) + dp(15),self.y + float(root.yRtText) + dp(17),dp(10))\
                                        if float(root.yRtText) > float(root.yLtText) else\
                                        (float(root.xRtText) + dp(15),self.y + float(root.yLtText) + dp(17),dp(10))



                             ################################  Arrows   ##########################################
                ################### Base Velocity Arrows   ##########################

                                ################## U Arrow ########################
                                Color:
                                    rgba: (1,1,1,0) if float(root.x1tText) - float(root.x0tText) < 30 else (0,0,0,1)
                                Triangle:
                                    points:float(root.x0tText),self.y + float(root.y0Text),float(root.x0tText)+dp(25),self.y + float(root.y0Text)+dp(5),float(root.x0tText)+dp(25),self.y + float(root.y0Text)-dp(5)

                                ################## The other 4 Base Arrows ########################
                                Color:
                                    rgba: (0,0,0,1)
                                Triangle:
                                    points:float(root.x0tText),self.y + float(root.y0Text),float(root.xL1utText),self.y + float(root.yL1utText),float(root.xL1dtText),self.y + float(root.yL1dtText)

                                Triangle:
                                    points:float(root.x0tText),self.y + float(root.y0Text),float(root.xL2utText),self.y + float(root.yL2utText),float(root.xL2dtText),self.y + float(root.yL2dtText)

                                Triangle:
                                    points:float(root.x1tText),self.y + float(root.y1Text),float(root.xR1utText),self.y + float(root.yR1utText),float(root.xR1dtText),self.y + float(root.yR1dtText)

                                Triangle:
                                    points:float(root.x1tText),self.y + float(root.y1Text),float(root.xR2utText),self.y + float(root.yR2utText),float(root.xR2dtText),self.y + float(root.yR2dtText)

                ##################  U Line Arrows  ####################
                                Color:
                                    rgba: (1,1,1,0) if float(root.x1tText) - float(root.x0tText) < dp(40) else (0,0,0,1)
                                Triangle:
                                    points:
                                        float(root.x0tText),self.y + float(root.y0Text)-dp(20),float(root.x0tText)+dp(20),\
                                        self.y + float(root.y0Text)-dp(20)+dp(3),float(root.x0tText)+dp(20),self.y + float(root.y0Text)-dp(20)-dp(3)
                                Triangle:
                                    points:
                                        float(root.x1tText),self.y + float(root.y1Text)-dp(20),float(root.x1tText)-dp(20),\
                                        self.y + float(root.y1Text)-dp(20)+dp(3),float(root.x1tText)-dp(20),self.y + float(root.y1Text)-dp(20)-dp(3)

                ##################  ΔVθ Line Arrows  ####################
                                Color:
                                    rgba: (1,1,1,0) if float(root.xRtText) - float(root.xLtText) < 25 else (0,0,0,1)
                                Triangle:
                                    points:
                                        ((float(root.xLtText),self.y + float(root.yRtText) + dp(20),float(root.xLtText)+ dp(20),self.y + float(root.yRtText) + dp(20) + dp(3),\
                                        float(root.xLtText)+ dp(20),self.y + float(root.yRtText) + dp(20) - dp(3))\
                                        if root.tc_namemText == 'Compressor Middle' else\
                                        (float(root.xRtText),self.y + float(root.yRtText) + dp(20),float(root.xRtText)- dp(20),self.y + float(root.yRtText) + dp(20) + dp(3),\
                                        float(root.xRtText)- dp(20),self.y + float(root.yRtText) + dp(20) - dp(3)))\
                                        if float(root.yRtText) > float(root.yLtText) else\
                                        ((float(root.xLtText),self.y + float(root.yLtText) + dp(20),float(root.xLtText)+ dp(20),self.y + float(root.yLtText) + dp(20) + dp(3),\
                                        float(root.xLtText)+ dp(20),self.y + float(root.yLtText) + dp(20) - dp(3))\
                                        if root.tc_namemText == 'Compressor Middle' else\
                                        (float(root.xRtText),self.y + float(root.yLtText) + dp(20),float(root.xRtText)- dp(20),self.y + float(root.yLtText) + dp(20) + dp(3),\
                                        float(root.xRtText)- dp(20),self.y + float(root.yLtText) + dp(20) - dp(3)))

                #####################  Vx2 Line Arrows  ####################
                                Color:
                                    rgba: (1,1,1,0) if (float(root.yRtText) - float(root.y1Text)) < 25 else (0,0,0,1)
                                Triangle:
                                    points:
                                        (float(root.x1tText) + dp(20),self.y + float(root.y1Text),float(root.x1tText) + dp(20) + dp(3),\
                                        self.y + float(root.y1Text)+dp(20),float(root.x1tText) + dp(20) - dp(3),self.y + float(root.y1Text)+dp(20))\
                                        if float(root.xRtText) < float(root.x1tText) else\
                                        (float(root.xRtText)+ dp(20),self.y + float(root.y1Text),float(root.xRtText)+ dp(20) + dp(3),\
                                        self.y + float(root.y1Text) + dp(20),float(root.xRtText)+ dp(20) - dp(3),self.y + float(root.y1Text) + dp(20))

                                #####################  Vx1 Line Arrows  ####################
                                Color:
                                    rgba: (1,1,1,0) if (float(root.yLtText) - float(root.y0Text)) < 25 else (0,0,0,1)
                                Triangle:
                                    points:
                                        (float(root.x0tText) - dp(20),self.y + float(root.y0Text),float(root.x0tText) - dp(20) + dp(3),\
                                        self.y + float(root.y1Text) + dp(20),float(root.x0tText) - dp(20) - dp(3),self.y + float(root.y0Text)+dp(20))\
                                        if float(root.xLtText) > float(root.x0tText) else\
                                        (float(root.xLtText) - dp(20),self.y + float(root.y1Text),float(root.xLtText) - dp(20) + dp(3),\
                                        self.y + float(root.y1Text) + dp(20),float(root.xLtText) - dp(20) - dp(3),self.y + float(root.y1Text) + dp(20))

                            Label:
                                text: 'U'
                                pos: self.parent.x, self.parent.y - self.parent.height/2 + float(root.y0Text) -dp(35)

                            Label:
                                text: 'Vx2'
                                pos:
                                    (self.parent.x + float(root.UtpText)/2 + dp(40),\
                                    self.parent.y - self.parent.height/2 + float(root.y0Text)/2 + float(root.yRtText)/2)\
                                    if float(root.xRtText)<float(root.x1tText)\
                                    else\
                                    (self.parent.x - self.parent.width/2 + float(root.xRtText) + dp(40),\
                                    self.parent.y - self.parent.height/2 + float(root.y0Text)/2 + float(root.yRtText)/2)

                            Label:
                                text: 'Vx1' if root.tc_namemText == 'Compressor Middle' else 'Vx3'
                                pos:
                                    (self.parent.x - float(root.UtpText)/2 - dp(40),\
                                    self.parent.y - self.parent.height/2 + float(root.y0Text)/2 + float(root.yLtText)/2)\
                                    if float(root.xLtText)>float(root.x0tText)\
                                    else\
                                    (self.parent.x - self.parent.width/2 + float(root.xLtText) - dp(40),\
                                    self.parent.y - self.parent.height/2 + float(root.y0Text)/2 + float(root.yLtText)/2)

                            Label:
                                text: '\u0394V\u03B8'
                                pos:
                                    (-float(root.UtpText)/2-float(root.x0tText)+float(root.xLtText)+float(root.UtpText)*float(root.ptText)/2,\
                                    self.parent.y - self.parent.height/2 + float(root.yRtText) + dp(35))\
                                    if float(root.yRtText) > float(root.yLtText) else\
                                    (-float(root.UtpText)/2-float(root.x0tText)+float(root.xLtText)+float(root.UtpText)*float(root.ptText)/2,\
                                    self.parent.y - self.parent.height/2 + float(root.yLtText) + dp(35))

                            Label:
                                text:'1' if root.tc_namemText == 'Compressor Middle' else '3'
                                pos:
                                    (-float(root.UtpText)/2-float(root.x0tText)+float(root.xLtText) - dp(15),\
                                    self.parent.y - self.parent.height/2 + float(root.yRtText) + dp(17))\
                                    if float(root.yRtText) > float(root.yLtText) else\
                                    (-float(root.UtpText)/2-float(root.x0tText)+float(root.xLtText) - dp(15),\
                                    self.parent.y - self.parent.height/2 + float(root.yLtText) + dp(17))
                            Label:
                                text:'2'
                                pos:
                                    (-float(root.UtpText)/2-float(root.x0tText)+float(root.xRtText) + dp(15),\
                                    self.parent.y - self.parent.height/2 + float(root.yRtText) + dp(17))\
                                    if float(root.yRtText) > float(root.yLtText) else\
                                    (-float(root.UtpText)/2-float(root.x0tText)+float(root.xRtText) + dp(15),\
                                    self.parent.y - self.parent.height/2 + float(root.yLtText) + dp(17))



                        GridLayout:
                            cols:2
                            size_hint_y: 0.1

                            BoxLayout:
                                size_hint_x:0.3
                                padding:dp(10)
                                spacing:dp(10)
                                MDRectangleFlatIconButton:
                                    icon:'arrow-left-bold'
                                    md_bg_color:[0.4,.4,.4,1]
                                    text_color: [1,1,1,1]
                                    size_hint:0.25,1
                                    text:"Back"
                                    on_press:
                                        root.manager.current = "Main"
                                        root.manager.transition.direction = "right"
#                                        sv_tip.scroll_y = 1

                            BoxLayout:
                                size_hint_x:0.7
                                MDLabel:
                                    font_size: dp(13)
                                    color: 1,0,0,1
                                    text:
                                        ('*Tip triangles were ' + (str(round(100*(1-float(root.UtpText)/float(root.Utp_cText)),1))) + ' %' + ' scaled down in order to fit.')\
                                        if (float(root.UtpText)<float(root.Utp_cText)) else ''

                        MDBoxLayout:
                            orientation: 'vertical'
                            padding: dp(10),dp(0)
                            size_hint: 1,0.135
                            md_bg_color:0.18,0.18,0.18,1
                            canvas:
                                Color:
                                    rgba: 0.8,0.8,0.8,0.5
                                Line:
                                    width: dp(7.5)
                                    points: (self.x,self.height-dp(7.5),self.width,self.height-dp(7.5))
                            Label:
                                text: 'Velocity Triangles Analysis App/Dimensional Analysis/Tip '
                                font_size: dp(14)
                                color: 1,1,1,1
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'

                ScrollView:
                    size: root.height, root.width
                    size_hint: 1,0.25
                    scroll_wheel_distance: '150dp'
                    effect_cls: 'ScrollEffect'
                    id: sv_comp
                    GridLayout:
                        size_hint_y: 2.255
                        rows: 9
                        ############# Image Box ##############
                        FloatLayout:
                            size_hint_y: 0.4
                            canvas:
                                Color:
                                    rgba: 1,1,1,1
                                Rectangle:
                                    source: "images/new_images/comp_full1.png" if root.tc_namemText == 'Compressor Middle' else "images/new_images/turb_full.png"
                                    size: self.width ,self.height
                                    pos: self.x ,self.y

                        MDBoxLayout:
                            size_hint_y: 0.08
                            md_bg_color: 1,0.55,0,0.8

                            Label:
                                padding: dp(10),dp(0)
                                text: 'Triangles Comparison'
                                font_size: dp(20)
                                bold: True
                                underline: True
                                text_size: self.size
                                halign:'left'
                                valign: 'middle'

            ######################    Comparison FloatLayout ##########################
                        FloatLayout:
                            size_hint_y: 0.45
                            canvas:


            ########################  TIP  #######################################################
                ###################    Color of the Lines    ##################
                                Color:
                                    rgba:1,0,0,1
                ###################    Ut line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0t_cText),self.y + float(root.y0Text),float(root.x1t_cText),self.y + float(root.y1Text))


                ###################    V1t Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0t_cText),self.y +float(root.y0Text),float(root.xRt_cText),self.y +float(root.yRt_cText))

                ###################    W1t Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x1t_cText),self.y + float(root.y1Text),float(root.xRt_cText),self.y + float(root.yRt_cText))

                ###################    W2t Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x1t_cText),self.y + float(root.y1Text),float(root.xLt_cText),self.y + float(root.yLt_cText))

                ###################    V2t Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0t_cText),self.y + float(root.y0Text),float(root.xLt_cText),self.y + float(root.yLt_cText))

                                Color:
                                    rgba:(0,0,0,0) if float(root.x1tText) - float(root.x0tText) < 30 else (1,0,0,1)

            ########################     MIDDLE       #################################################

                                ###################    Color of the Lines    ##################
                                Color:
                                    rgba:0,0,0,1
                ###################    U line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0Text),self.y + float(root.y0Text),float(root.x1Text),self.y + float(root.y1Text))

                ###################    V1 Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0Text),self.y +float(root.y0Text),float(root.xRText),self.y +float(root.yRText))

                ###################    W1 Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x1Text),self.y + float(root.y1Text),float(root.xRText),self.y + float(root.yRText))

                ###################    W2 Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x1Text),self.y + float(root.y1Text),float(root.xLText),self.y + float(root.yLText))

                ###################    V2 Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0Text),self.y + float(root.y0Text),float(root.xLText),self.y + float(root.yLText))

                                Color:
                                    rgba: (0,0,0,0) if float(root.x1Text) - float(root.x0Text) < 30 else (0,0,0,1)

            #########################     HUB     ##################################################

                ###################    Color of the Lines    ##################
                                Color:
                                    rgba:0,0,1,1
                ###################    Uh line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0h_cText),self.y + float(root.y0Text),float(root.x1h_cText),self.y + float(root.y1Text))

                ###################    V1h Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0h_cText),self.y +float(root.y0Text),float(root.xRh_cText),self.y +float(root.yRh_cText))

                ###################    W1h Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x1h_cText),self.y + float(root.y1Text),float(root.xRh_cText),self.y + float(root.yRh_cText))

                ###################    W2h Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x1h_cText),self.y + float(root.y1Text),float(root.xLh_cText),self.y + float(root.yLh_cText))

                ###################    V2h Line    ##########################
                                Line:
                                    width: dp(1.5)
                                    points: (float(root.x0h_cText),self.y + float(root.y0Text),float(root.xLh_cText),self.y + float(root.yLh_cText))

                                Color:
                                    rgba: (0,0,0,0) if float(root.x1hText) - float(root.x0hText) < 30 else (0,0,1,1)

                                #############  Top right corner box ############

                                Color:
                                    rgba: 0,0,0,1
                                Line:
                                    width: dp(1)
                                    rectangle: (self.x + self.width - dp(115),self.y + dp(25),dp(90),dp(40))

                                ##### HUB ###
                                Color:
                                    rgba:0,0,1,1
                                Line:
                                    width: dp(1)
                                    points: (self.x + self.width - dp(80),self.y + dp(57.5),self.x + self.width - dp(40),self.y + dp(57.5))

                                ##### MID ###
                                Color:
                                    rgba: 0,0,0,1
                                Line:
                                    width: dp(1)
                                    points: (self.x + self.width - dp(80),self.y + dp(45),self.x + self.width - dp(40),self.y + dp(45))

                                #####  TIP  #####
                                Color:
                                    rgba:1,0,0,1
                                Line:
                                    width: dp(1)
                                    points: (self.x + self.width - dp(80),self.y + dp(32.5),self.x + self.width - dp(40),self.y + dp(32.5))

                                Color:
                                    rgba:1,1,1,1
                                Line:
                                    width: dp(9.25)
                                    rectangle: (self.x+9.25, self.y + 9.25, self.width-18.5, self.height-18.5)

                                Color:
                                    rgba:0,0,0,1
                                Line:
                                    width: dp(1.)
                                    rectangle: (self.x+20, self.y + 20, self.width-40, self.height-40)
                            Label:
                                font_size: dp(11)
                                pos: self.parent.width/2 - dp(100), self.parent.y - self.parent.height/2 + dp(58.5)
                                text: 'Hub'

                            Label:
                                font_size: dp(11)
                                pos: self.parent.width/2 - dp(100), self.parent.y - self.parent.height/2 + dp(46)
                                text: 'Mid'

                            Label:
                                font_size: dp(11)
                                pos: self.parent.width/2 - dp(100), self.parent.y - self.parent.height/2 + dp(33.5)
                                text: 'Tip'



#################################   Stator Camber Line drawings   ################################
                        MDBoxLayout:
                            size_hint_y: 0.08
                            md_bg_color: 1,0.55,0,0.8

                            Label:
                                padding: dp(10),dp(0)
                                text: 'Stator mean camber lines'
                                font_size: dp(20)
                                bold: True
                                underline: True
                                text_size: self.size
                                halign:'left'
                                valign: 'middle'
                        FloatLayout:
                            size_hint_y: 0.45
                            canvas:
                                Color:
                                    rgba:0,0,0,1
                                Line:
                                    width: dp(1.)
                                    rectangle: (self.x+20, self.y + 20, self.width-40, self.height-40)
                            ############# Hub Stator Camber Lines  #################
                                Color:
                                    rgba: 0,0,1,1
                                Line:
                                    width: dp(1.5)
                                    bezier:
                                        (float(root.xLh_cambText),self.y + float(root.yLh_cambText),
                                        float(root.xs_centText),self.y +float(root.ys_centText),
                                        float(root.xRh_cambText),self.y +float(root.yRh_cambText))

                            ############# Mid Stator Camber Lines  #################
                                Color:
                                    rgba: 0,0,0,1
                                Line:
                                    width: dp(1.5)
                                    bezier:
                                        (float(root.xLm_cambText),self.y + float(root.yLm_cambText),
                                        float(root.xs_centText),self.y +float(root.ys_centText),
                                        float(root.xRm_cambText),self.y +float(root.yRm_cambText))

                            ############# Tip Stator Camber Lines  #################
                                Color:
                                    rgba: 1,0,0,1
                                Line:
                                    width: dp(1.5)
                                    bezier:
                                        (float(root.xLt_cambText),self.y + float(root.yLt_cambText),
                                        float(root.xs_centText),self.y +float(root.ys_centText),
                                        float(root.xRt_cambText),self.y +float(root.yRt_cambText))

                                               #############  Top right corner box ############

                                Color:
                                    rgba: 0,0,0,1
                                Line:
                                    width: dp(1)
                                    rectangle: (self.x + self.width - dp(115),self.y + self.height - dp(65),dp(90),dp(40))

                                ##### HUB ###
                                Color:
                                    rgba:0,0,1,1
                                Line:
                                    width: dp(1)
                                    points: (self.x + self.width - dp(80),self.y +self.height - dp(32.5),self.x + self.width - dp(40),self.y + self.height - dp(32.5))

                                ##### MID ###
                                Color:
                                    rgba: (0,0,0,1)
                                Line:
                                    width: dp(1)
                                    points: (self.x + self.width - dp(80),self.y + self.height - dp(45),self.x + self.width - dp(40),self.y + self.height - dp(45))

                                #####  TIP  #####
                                Color:
                                    rgba:1,0,0,1
                                Line:
                                    width: dp(1)
                                    points: (self.x + self.width - dp(80),self.y + self.height  - dp(57.5),self.x + self.width - dp(40),self.y + self.height - dp(57.5))

                            Label:
                                font_size: dp(11)
                                pos: self.parent.width/2 - dp(100), self.parent.y + self.parent.height/2 - dp(30.5)
                                text: 'Hub'

                            Label:
                                font_size: dp(11)
                                pos: self.parent.width/2 - dp(100), self.parent.y + self.parent.height/2 - dp(43)
                                text: 'Mid'

                            Label:
                                font_size: dp(11)
                                pos: self.parent.width/2 - dp(100), self.parent.y + self.parent.height/2 - dp(55.5)
                                text: 'Tip'

                        MDBoxLayout:
                            size_hint_y: 0.08
                            md_bg_color: 1,0.55,0,0.8

                            Label:
                                padding: dp(10),dp(0)
                                text: 'Rotor mean camber lines'
                                font_size: dp(20)
                                bold: True
                                underline: True
                                text_size: self.size
                                halign:'left'
                                valign: 'middle'

                        FloatLayout:
                            size_hint_y: 0.45
                            canvas:
                                Color:
                                    rgba:0,0,0,1
                                Line:
                                    width: dp(1.)
                                    rectangle: (self.x+20, self.y + 20, self.width-40, self.height-40)
                            ############# Hub Rotor Camber Lines  #################
                                Color:
                                    rgba: 0,0,1,1

                                Line:
                                    width: dp(1.5)
                                    bezier:
                                        (float(root.xLh_cambText),self.y + float(root.yLh_rotorText),
                                        float(root.xs_centText),self.y +float(root.ys_centText),
                                        float(root.xRh_cambText),self.y +float(root.yRh_rotorText))

                            ############# Mid Rotor Camber Lines  #################
                                Color:
                                    rgba: 0,0,0,1
                                Line:
                                    width: dp(1.5)
                                    bezier:
                                        (float(root.xLm_cambText),self.y + float(root.yLm_rotorText),
                                        float(root.xs_centText),self.y +float(root.ys_centText),
                                        float(root.xRm_cambText),self.y +float(root.yRm_rotorText))

                            ############# Tip Rotor Camber Lines  #################
                                Color:
                                    rgba: 1,0,0,1
                                Line:
                                    width: dp(1.5)
                                    bezier:
                                        (float(root.xLt_cambText),self.y + float(root.yLt_rotorText),
                                        float(root.xs_centText),self.y +float(root.ys_centText),
                                        float(root.xRt_cambText),self.y +float(root.yRt_rotorText))

                                               #############  Top right corner box ############

                                Color:
                                    rgba: 0,0,0,1
                                Line:
                                    width: dp(1)
                                    rectangle: (self.x + self.width - dp(115),self.y + self.height - dp(65),dp(90),dp(40))

                                ##### HUB ###
                                Color:
                                    rgba:0,0,1,1
                                Line:
                                    width: dp(1)
                                    points: (self.x + self.width - dp(80),self.y +self.height - dp(32.5),self.x + self.width - dp(40),self.y + self.height - dp(32.5))

                                ##### MID ###
                                Color:
                                    rgba: (0,0,0,1)
                                Line:
                                    width: dp(1)
                                    points: (self.x + self.width - dp(80),self.y + self.height - dp(45),self.x + self.width - dp(40),self.y + self.height - dp(45))

                                #####  TIP  #####
                                Color:
                                    rgba:1,0,0,1
                                Line:
                                    width: dp(1)
                                    points: (self.x + self.width - dp(80),self.y + self.height  - dp(57.5),self.x + self.width - dp(40),self.y + self.height - dp(57.5))

                            Label:
                                font_size: dp(11)
                                pos: self.parent.width/2 - dp(100), self.parent.y + self.parent.height/2 - dp(30.5)
                                text: 'Hub'

                            Label:
                                font_size: dp(11)
                                pos: self.parent.width/2 - dp(100), self.parent.y + self.parent.height/2 - dp(43)
                                text: 'Mid'

                            Label:
                                font_size: dp(11)
                                pos: self.parent.width/2 - dp(100), self.parent.y + self.parent.height/2 - dp(55.5)
                                text: 'Tip'
            ####################    Button  ####################
                        GridLayout:
                            cols:2
                            size_hint_y: 0.1

                            BoxLayout:
                                size_hint_x:0.3
                                padding:dp(10)
                                spacing:dp(10)
                                MDRectangleFlatIconButton:
                                    icon:'arrow-left-bold'
                                    md_bg_color:[0.4,.4,.4,1]
                                    text_color: [1,1,1,1]
                                    size_hint:0.25,1
                                    text:"Back"
                                    on_press:
                                        root.manager.current = "Main"
                                        root.manager.transition.direction = "right"
#                                        sv_comp.scroll_y = 1


                            BoxLayout:
                                size_hint_x:0.7

                        MDBoxLayout:
                            orientation: 'vertical'
                            padding: dp(10),dp(0)
                            size_hint: 1,0.135
                            md_bg_color:0.18,0.18,0.18,1
                            canvas:
                                Color:
                                    rgba: 0.8,0.8,0.8,0.5
                                Line:
                                    width: dp(7.5)
                                    points: (self.x,self.height-dp(7.5),self.width,self.height-dp(7.5))
                            Label:
                                text: 'Velocity Triangles Analysis App/Dimensional Analysis/ Velocity Triangles Comparison '
                                font_size: dp(14)
                                color: 1,1,1,1
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'


