WindowManager:
    VelocityTriangles:
    NewWindow:

<P>:

<P2>:

<P3>:

<Label>
    color: [0,0,0,1]
    id: kappa
    size_hint_x: 1
    

<TextInput>
    size_hint_x: 1
    spacing: 5
    write_tab: False
    input_filter:'float'
    #do_cursor_movement(cursor_down)
    cursor_color: 0.2,0.5,0,0.8
    cursor_width: '2dp'


<ToggleButton>
    size_hint: 0.5,1

<Slider>
    size_hint_x: 0.7
    value_track: True
    value_track_color: [0.2,0.2,0.2,0.8]


<VelocityTriangles>:
    name: "Main"

    p:p
    f:f
    rn:rn
    a1:a1
    a2:a2
    a3:a3
    b1:b1
    b2:b2
    b3:b3

    d1:d1
    d2:d2
    d3:d3
    rh2t1:rh2t1
    rh2t2:rh2t2
    rh2t3:rh2t3
    n:n

    ScrollView:
        size: root.height, root.width
        size_hint: 1,1
        scroll_wheel_distance: '40dp'

####################  Overall Grid  ############################
        GridLayout:
            rows: 11
            size_hint_y:1.2
############ Overall Title ######################
            GridLayout:
                cols:2
                size_hint_y:0.08
                orientation: 'horizontal'
                canvas:
                    Color:
                        rgba: 0.066,0.392,0.505,0.768
                    Rectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    size_hint_x:0.9
                    text: "Velocity Triangles Analysis "
                    bold: True
                    font_size:dp(25)
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'

                BoxLayout:
                    size_hint_x:0.1
                    padding:dp(3)
                    Button:
                        size_hint: 0.9,0.6
                        pos_hint: {'x':0.05,'y':0.2}
                        #background_color: 0,0,0,1
                        background_normal: 'images/info-4x.png'
                        #background_down: 'down.png'
                        on_press:root.showbubble() if root.b%2!=1 else root.destroybubble()    

            BoxLayout:
                padding: 10
                size_hint_y: 0.08
                canvas:
                    Color:
                        rgba: 0.333,0.596,0.635,0.9
                    Rectangle:
                        pos: self.pos
                        size: self.size

                Label:
                    text:'Repeating Stage'
                    bold: True if slider0.value==0 else False
                    #font_size: root.fontsize(self.text)
                    font_size: dp(15)
                    size: self.width,self.height
                    halign: 'left'
                    valign: 'middle'

                Slider:
                    size_hint_x:0.6
                    min: 0
                    max: 1
                    step: 1
                    id: slider0

                    cursor_height: dp(28)
                    cursor_width: dp(28)

                Label:
                    text:'   Non Repeating Stage'
                    bold: True if slider0.value==1 else False
                    font_size: dp(15)

############ Keno anamesa sto switch kai ta inputs ###########################
            BoxLayout:
                size_hint_y: 0.01
                canvas:
                    Color:
                        rgba:0.6862,0.9333,0.9333,0.737
                    Rectangle:
                        pos: self.pos
                        size: self.size

########### Grid for the Text Inputs #########################
            GridLayout:
                spacing: dp(3)
                size_hint_y: 0.4
                cols: 4
                canvas:
                    Color:
                        rgba: 0.6862,0.9333,0.9333,0.737
                    Rectangle:
                        pos: self.pos
                        size: self.size

                Label:
                    font_size:dp(11)
                    text:"Loading Coefficient \u03C8 : "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                    size_hint_x:0.33
                TextInput:
                    text: '' if slider1.value==0  else str(round(slider1.value,3))
                    id: p
                    multiline: False
                    write_tab: False

                Label:
                    font_size:dp(11)
                    text: " [ - ] "
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'
                    size_hint_x:0.3
                Slider:
                    id: slider1
                    min: 0
                    max: 2.5
                    step: 0.01
                    value: 0

                Label:
                    font_size:dp(11)
                    text:"Flow Coefficient \u03C6 : "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    text: '' if slider2.value==0  else str(round(slider2.value,3))
                    id: f
                    multiline: False
                Label:
                    font_size:dp(11)
                    text: " [ - ] "
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'
                    size_hint_x:0.3 
                Slider:
                    id: slider2
                    min: 0
                    max: 2
                    step: 0.01
                    value:0

                Label:
                    font_size:root.l*dp(11)
                    text:"Reaction Coefficient Rn : "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    text: '' if slider3.value==0  else str(round(slider3.value,3))
                    multiline: False
                    id: rn
                Label:
                    font_size:dp(11)
                    text: " [ - ] "
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'
                    size_hint_x:0.3
                Slider:
                    id: slider3
                    min: 0
                    max: 1.5
                    step: 0.01
                    value: 0

                Label:
                    font_size:dp(11)
                    text:"Inlet absolute angle \u03B11 : "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    text: '' if slider4.value==0  else str(round(slider4.value,3))
                    multiline: False
                    id: a1
                Label:
                    font_size:dp(11)
                    text: " [ \u00B0 ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'
                    size_hint_x:0.3
                Slider:
                    id: slider4
                    min: -75
                    max: 75
                    step: 0.1

                Label:
                    font_size:dp(11)
                    text:"Exit absolute angle \u03B12 : "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    text: '' if slider5.value==0  else str(round(slider5.value,3))
                    multiline: False
                    id: a2
                Label:
                    font_size:dp(11)
                    text: " [ \u00B0 ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'
                    size_hint_x:0.3
                Slider:
                    id: slider5
                    min: -75
                    max: 75
                    step: 0.1

                Label:
                    font_size:dp(11)
                    text:"Inlet absolute angle \u03B13 : "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    disabled: slider0.value==0
                    text: '' if slider6.value==0  else str(round(slider6.value,3))
                    multiline: False
                    id: a3
                Label:
                    font_size:dp(11)
                    text: " [ \u00B0 ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'
                    size_hint_x:0.3
                Slider:
                    id: slider6
                    min: -75
                    max: 75
                    step: 0.1
                    disabled: slider0.value == 0

                Label:
                    font_size:dp(11)
                    text:"Inlet relative angle \u03B21 : "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    text: '' if slider7.value==0  else str(round(slider7.value,3))
                    multiline: False
                    id: b1
                Label:
                    font_size:dp(11)
                    text: " [ \u00B0 ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'
                    size_hint_x:0.3

                Slider:
                    id: slider7
                    min: -75
                    max: 75
                    step: 0.1
                Label:
                    font_size:dp(11)
                    text:"Exit relative angle \u03B22 : "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:

                    text: '' if slider8.value==0  else str(round(slider8.value,3))
                    multiline: False
                    id: b2
                Label:
                    font_size:dp(11)
                    text: " [ \u00B0 ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'
                    size_hint_x:0.3

                Slider:
                    id: slider8
                    min: -75
                    max: 75
                    step: 0.1

                Label:
                    font_size:dp(11)
                    text:"Inlet relative angle \u03B23 : "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    disabled: slider0.value==0
                    text: '' if slider9.value==0  else str(round(slider9.value,3))
                    multiline: False
                    id: b3
                Label:
                    font_size:dp(11)
                    text: " [ \u00B0 ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'
                    size_hint_x:0.3

                Slider:
                    id: slider9
                    min: -75
                    max: 75
                    step: 0.1
                    disabled: slider0.value == 0

            BoxLayout:
                size_hint_y: 0.01
                padding:dp(5)
                canvas:
                    Color:
                        rgba: 0.6862,0.9333,0.9333,0.737
                    Rectangle:
                        pos: self.pos
                        size: self.size

############ Deyteros Titlos
            BoxLayout:
                size_hint_y: 0.08
                padding:dp(5)
                canvas:
                    Color:
                        rgba: 0.066,0.392,0.505,0.768
                    Rectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    text: " Dimensional Analysis "
                    bold: True
                    font_size:dp(25)

            BoxLayout:
                size_hint_y: 0.08
                padding: dp(11)
                canvas:
                    Color:
                        rgba: 0.333,0.596,0.635,0.9
                    Rectangle:
                        pos: self.pos
                        size: self.size

                Label:
                    #font_size: root.fontsize(self.text)
                    font_size: dp(15)
                    bold: True if slider10.value==0 else False
                    text:"Parallel Annulus"
                    size_hint_x: 1

                Slider:
                    size_hint_x:0.6
                    min: 0
                    max: 1
                    step: 1
                    id: slider10
                    cursor_height: dp(28)
                    cursor_width: dp(28)
                Label:
                    #font_size: root.fontsize(self.text)
                    font_size: dp(15)
                    bold: True if slider10.value==1 else False
                    text:"    Non Parallel Annulus"
                    size_hint_x: 1

            BoxLayout:
                size_hint_y: 0.01
                padding:dp(5)
                canvas:
                    Color:
                        rgba: 0.6862,0.9333,0.9333,0.737
                    Rectangle:
                        pos: self.pos
                        size: self.size

            GridLayout:
                spacing: dp(3)
                size_hint_y: 0.31
                cols: 3
                canvas:
                    Color:
                        rgba: 0.6862,0.9333,0.9333,0.737

                    Rectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    font_size:dp(11)
                    text:"Tip Diameter at Stage 1: "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    multiline: False
                    id: d1
                Label:
                    font_size:dp(11)
                    text: " [ m ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'

                Label:
                    font_size:dp(11)
                    text:"Tip Diameter at Stage 2: "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    disabled: slider10.value==0
                    multiline: False
                    id: d2
                Label:
                    font_size:dp(11)
                    text: " [ m ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'

                Label:
                    font_size:dp(11)
                    text:"Tip Diameter at Stage 3: "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    disabled: slider10.value==0
                    multiline: False
                    id: d3
                Label:
                    font_size:dp(11)
                    text: " [ m ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'

                Label:
                    font_size:dp(11)
                    text:" Hub2Tip ratio at Stage 1: "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    multiline: False
                    id: rh2t1
                Label:
                    font_size:dp(11)
                    text: " [ - ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'

                Label:
                    font_size:dp(11)
                    text:" Hub2Tip ratio at Stage 2: "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    disabled: slider10.value==0
                    multiline: False
                    id: rh2t2
                Label:
                    font_size:dp(11)
                    text: " [ - ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'

                Label:
                    font_size:dp(11)
                    text:" Hub2Tip ratio at Stage 1: "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    disabled: slider10.value==0
                    multiline: False
                    id: rh2t3
                Label:
                    font_size:dp(11)
                    text: " [ - ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'

                Label:
                    font_size:dp(11)
                    text:" Rotational Speed : "
                    text_size: self.size
                    halign: 'right'
                    valign: 'middle'
                TextInput:
                    multiline: False
                    id: n
                Label:
                    font_size:dp(11)
                    text: " [ rpm ]"
                    text_size: self.size
                    halign: 'left'
                    valign: 'middle'


            BoxLayout:
                size_hint_y: 0.07
                padding:dp(5)
                canvas:
                    Color:
                        rgba: 0.6862,0.9333,0.9333,0.737
                    Rectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    size_hint_x:0.325
                    text: ""
                Button:
                    id:oti
                    size_hint_x:0.333
                    text: "Velocity Analysis"
                    font_size:dp(14)
                    color: [1,1,1,1]
                    on_release:
                        root.systemsolver()
                        root.dml()
                        if root.k == 4 :\
                        app.root.current = "new"
                        root.manager.transition.direction = "left"
                Label:
                    size_hint_x:0.325
                    text: ""

            BoxLayout:
                size_hint_y: 0.01
                padding:dp(5)
                canvas:
                    Color:
                        rgba: 0.6862,0.9333,0.9333,0.737
                    Rectangle:
                        pos: self.pos
                        size: self.size

<NewWindow>:
    name: "new"

    ScrollView:
        size: root.height, root.width
        size_hint: 1,1
        scroll_wheel_distance: '40dp'

        GridLayout:
            rows: 6
            size_hint: 1,1.66

############ First Title ####################
            BoxLayout:
                size_hint_y: 0.08
                canvas:
                    Color:
                        rgba: 0.066,0.392,0.505,0.768
                    Rectangle:
                        pos: self.pos
                        size: self.size

                Label:
                    text: 'Velocity Analysis'
                    font_size: dp(25)
                    bold: True

############ Image Box ##############
            BoxLayout:
                size_hint_y: 0.4
                canvas:
                    Color:
                        rgba: 0.6862,0.9333,0.9333,0.737
                    Rectangle:
                        pos: self.pos
                        size: self.size
                    Rectangle:
                        source: "images/compressor.png" if root.tc_nameText == 'Compressor' else "images/turbine.png"
                        size: self.width,self.height
                        pos: self.x,self.y

            BoxLayout:
                size_hint_y: 0.08
                canvas:
                    Color:
                        rgba: 0.066,0.392,0.505,0.768
                    Rectangle:
                        pos: self.pos
                        size: self.size
                    Color:
                        rgba:0,0,0,1
                    Line:
                        width: dp(1.5)
                        points: (self.x, self.y + self.height, self.x + self.width, self.y + self.height)
                    Line:
                        width: dp(3)
                        points: (self.x, self.y , self.x, self.y + self.height)
                    Line:
                        width: dp(3)
                        points: (self.x + self.width, self.y,self.x+ self.width, self.y + self.height)

                    Line:
                        width: dp(3)
                        points: (self.x, self.y, self.x + self.width, self.y)
                Label:
                    text: 'Middle Velocity Triangles'
                    font_size: dp(20)
                    bold: True

    ######################GRid me ta grapta apotelesmata #############################
            GridLayout:
                cols:2
                size_hint_y: 0.65

    ###############   Grid gia diaxorismo titlou apo ta apotelesmata #######################
                GridLayout:
                    rows:2
                    size_hint_x:0.5

    ##################################   Titlos    ####################################
                    BoxLayout:
                        size_hint_y:0.12
                        spacing:10
                        canvas:
                            Color:
                                rgba: 0.066,0.392,0.505,0.768
                            Rectangle:
                                pos: self.pos
                                size: self.size
                            Color:
                                rgba:0,0,0,1
#                            Line:
#                                width: dp(1.5)
#                                points: (self.x,self.y + self.height, self.x+self.width,self.y + self.height)
                            Line:
                                width: dp(3.)
                                points: (self.x, self.y, self.x, self.y+self.height)
                            Line:
                                width: dp(3.)
                                points: (self.x+self.width, self.y, self.x + self.width, self.y+self.height)
                        Label:
                            text:'Coefficients and Angles'
                            font_size: dp(15)
                            bold:True
                            text_size: self.size
                            halign: 'center'
                            valign: 'middle'

    ################   Grid apotelespata aristera    ###########################
                    GridLayout:
                        cols:3
                        canvas:
                            Color:
                                rgba: 0.6862,0.9333,0.9333,0.737
                            Rectangle:
                                pos: self.pos
                                size: self.size
                            Color:
                                rgba:0,0,0,1
                            Line:
                                width: dp(3.)
                                points: (self.x, self.y, self.x, self.y+self.height)
                            Line:
                                width: dp(3.)
                                points: (self.x+self.width, self.y, self.x + self.width, self.y+self.height)
                            Line:
                                width: dp(3)
                                points: (self.x, self.y, self.x + self.width, self.y)
                            Line:
                                width: dp(1.5)
                                points: (self.x, self.y+self.height, self.x + self.width, self.y+self.height)

                        GridLayout:
                            rows:9
                            size_hint_x:0.67

                            Label:
                                font_size:dp(11)
                                text:"Loading Coefficient \u03C8 : "
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:"Flow Coefficient \u03C6 : "
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:"Reaction Coefficient Rn : "
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:"Inlet absolute angle \u03B11 : "
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:"Exit absolute angle \u03B12 : "
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:"Inlet absolute angle \u03B13 : "
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:"Inlet relative angle \u03B21 : "
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:"Exit relative angle \u03B22 : "
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:"Inlet relative angle \u03B23 : "
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'


                        GridLayout:
                            rows:9
                            size_hint_x:0.22

                            Label:
                                text: root.pText
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.fText
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.rnText
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.a1Text if root.tc_nameText == 'Compressor' else '------'
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.a2Text
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text:'------' if root.tc_nameText == 'Compressor' else root.a1Text
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.b1Text if root.tc_nameText == 'Compressor' else '------'
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.b2Text
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                #text: root.b3Text
                                text:'------' if root.tc_nameText == 'Compressor' else root.b1Text
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'

                        GridLayout:
                            rows:9
                            size_hint_x:0.11

                            Label:
                                text: '[ - ]'
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ - ]'
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ - ]'
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ \u00B0 ]'
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ \u00B0 ]'
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ \u00B0 ]'
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ \u00B0 ]'
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ \u00B0 ]'
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                #text: root.b3Text
                                text:'[ \u00B0 ]'
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'

    ############ Deksi grid to opoio diaxorizei ton titlo apo ta deksio apotelesmata ####################
                GridLayout:
                    rows:2
                    size_hint_x:0.5
    ##################  Titlos ###############################
                    BoxLayout:
                        size_hint_y:0.12
                        spacing:10
                        canvas:
                            Color:
                                rgba: (0.066,0.392,0.505,0.768) if root.check == 0 else (0.6862,0.9333,0.9333,0.737)
                            Rectangle:
                                pos: self.pos
                                size: self.size
                            Color:
                                rgba: (0,0,0,1) if root.check == 0 else (0,0,0,0)

                            Line:
                                width: dp(3.)
                                points: (self.x+ self.width, self.y,self.x+ self.width, self.y + self.height)
#                           Line:
#                               width: dp(1.5)
#                               points: (self.x, self.y + self.height,self.x+ self.width, self.y + self.height)


                        Label:
                            text:'Dimensional Velocities' if root.check == 0 else ''
                            font_size: dp(15)
                            bold:True
                            text_size: self.size
                            halign: 'center'
                            valign: 'middle'

    ################   Grid apotelespatvn deksia   ########################
                    GridLayout:
                        cols:3
                        canvas:
                            Color:
                                rgba: 0.6862,0.9333,0.9333,0.737
                            Rectangle:
                                pos: self.pos
                                size: self.size
                            Color:
                                rgba: (0,0,0,1) if root.check == 0 else (0,0,0,0)
                            Line:
                                width: dp(3.)
                                points: (self.x+self.width, self.y, self.x+self.width, self.y+self.height)
                            Line:
                                width: dp(1.5)
                                points: (self.x, self.y+self.height,self.x+ self.width, self.y+self.height)
                            Line:
                                width: dp(3)
                                points: (self.x, self.y,self.x+ self.width, self.y)

                        GridLayout:
                            rows:11
                            size_hint_x:0.55

                            Label:
                                font_size:dp(11)
                                text:' Middle rotational \n speed Um   ' if root.check == 0 else ''
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'


                            Label:
                                font_size:dp(11)
                                text:" Axial Velocity Vx " if root.check == 0 else ''
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:(" Inlet relative \n velocity V1   "if root.tc_nameText == 'Compressor' else " Exit relative \n velocity V3   ") if root.check == 0 else ''
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:" Exit absolute \n velocity V2   " if root.check == 0 else ''
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:(" Inlet relative \n velocity W1   "if root.tc_nameText == 'Compressor' else " Exit relative \n velocity W3   ") if root.check == 0 else ''
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:" Exit relative \n velocity W2   "  if root.check == 0 else ''
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'
                            Label:
                                font_size:dp(11)
                                text:" Absolute rotary \n velocity V\u03B81   " if root.check == 0 else ''
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'
                            Label:
                                font_size:dp(11)
                                text:" Absolute rotary \n velocity V\u03B82  " if root.check == 0 else ''
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'
                            Label:
                                font_size:dp(11)
                                text:" Absolute rotary \n velocity W\u03B81   " if root.check == 0 else ''
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'
                            Label:
                                font_size:dp(11)
                                text:" Absolute rotary \n velocity W\u03B82  " if root.check == 0 else ''
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'

                            Label:
                                font_size:dp(11)
                                text:" Difference of rotary \n velocity DV\u03B8   " if root.check == 0 else ''
                                text_size: self.size
                                halign: 'right'
                                valign: 'middle'


                        GridLayout:
                            rows:11
                            size_hint_x:0.25

                            Label:
                                text: root.UmText
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'

                            Label:
                                text: root.VxText
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.V1Text
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                #text: root.a1Text if slider0.value == 0 else '------'
                                text: root.V2Text
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.W1Text
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.W2Text
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.Vth1Text
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.Vth2Text
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.Wth1Text
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.Wth2Text
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                            Label:
                                text: root.DVthText
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'center'
                                valign: 'middle'
                        GridLayout:
                            rows:11
                            size_hint_x:0.2

                            Label:
                                text: '[ m/s ]' if root.check == 0 else ''
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ m/s ]' if root.check == 0 else ''
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ m/s ]' if root.check == 0 else ''
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ m/s ]' if root.check == 0 else ''
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ m/s ]' if root.check == 0 else ''
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ m/s ]' if root.check == 0 else ''
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text:'[ m/s ]' if root.check == 0 else ''
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ m/s ]' if root.check == 0 else ''
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text:'[ m/s ]' if root.check == 0 else ''
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                text: '[ m/s ]' if root.check == 0 else ''
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'
                            Label:
                                #text: root.b3Text
                                text:'[ m/s ]' if root.check == 0 else ''
                                font_size:dp(11)
                                text_size: self.size
                                halign: 'left'
                                valign: 'middle'




    ########Box sthn mesh . Kato apo ta apotelesmata (Ekei pou tha einai ta trigwna) ###########
            FloatLayout:
                size_hint_y: 0.4
                canvas:
                    Color:
                        rgba: 0.6862,0.9333,0.9333,0.737
                    Rectangle:
                        pos: self.pos
                        size: self.size

    ################ Drawing Area for the triangles  ##########################
                    Color:
                        rgba:0.5862,0.9333,0.9333,0.737
                    Rectangle:
                        pos:self.x+20, self.y
                        size:self.width-40, self.height-20

                    Color:
                        rgba:0,0,0,1
                    Line:
                        width: dp(1.)
                        rectangle: (self.x+20, self.y, self.width-40, self.height-20)

    ###################    Color of the Lines    ##################
                    Color:
                        rgba:0,0,0,1
    ###################    U line    ##########################
                    Line:
                        width: dp(1.5)
                        points: (float(root.x0Text),float(root.y0Text),float(root.x1Text),float(root.y1Text))

    ###################    V1 Line    ##########################
                    Line:
                        width: dp(1.5)
                        points: (float(root.x0Text),float(root.y0Text),float(root.xRText),float(root.yRText))

    ###################    W1 Line    ##########################
                    Line:
                        width: dp(1.5)
                        points: (float(root.x1Text),float(root.y1Text),float(root.xRText),float(root.yRText))

    ###################    W2 Line    ##########################
                    Line:
                        width: dp(1.5)
                        points: (float(root.x1Text),float(root.y1Text),float(root.xLText),float(root.yLText))

    ###################    V2 Line    ##########################
                    Line:
                        width: dp(1.5)
                        points: (float(root.x0Text),float(root.y0Text),float(root.xLText),float(root.yLText))

    ########### Lines, Dash lines and Labels ###################
    ###################    U dashLine    ##########################
                    Line:
                        width: dp(1)
                        points: (float(root.x0Text),float(root.y0Text)-dp(20),float(root.x1Text),float(root.y1Text)-dp(20))

    ###################    U Dash lines    ##########################
                    Line:
                        width: dp(1)
                        points: (float(root.x0Text),float(root.y0Text),float(root.x0Text),float(root.y0Text)-dp(30))
                        dash_length: dp(5)
                        dash_offset: dp(5)
                    Line:
                        width: dp(1)
                        points: (float(root.x1Text),float(root.y0Text),float(root.x1Text),float(root.y0Text)-dp(30))
                        dash_length: dp(5)
                        dash_offset: dp(5)

    ###################    Vx Line    ##########################
                    Line:
                        width: dp(1)
                        points:
                            (float(root.x1Text) + dp(20),float(root.y0Text),float(root.x1Text) + dp(20),float(root.yRText))\
                            if float(root.xRText) < float(root.x1Text) else\
                            (float(root.xRText)+ dp(20),float(root.y0Text),float(root.xRText)+ dp(20),float(root.yRText))

    ###################    Vx Dash lines    ##########################
                    Line:
                        width: dp(1)
                        points:
                            (float(root.x1Text),float(root.y1Text),float(root.x1Text) + dp(30),float(root.y0Text))\
                            if float(root.xRText) < float(root.x1Text) else\
                            (float(root.x1Text),float(root.y0Text),float(root.xRText) + dp(30) ,float(root.y1Text))
                        dash_length: dp(5)
                        dash_offset: dp(5)
                    Line:
                        width: dp(1)
                        points:
                            (float(root.xRText),float(root.yRText),float(root.x1Text) + dp(30),float(root.yRText))\
                            if float(root.xRText) < float(root.x1Text)  else\
                            (float(root.xRText),float(root.yRText),float(root.xRText)+dp(30),float(root.yRText))
                        dash_length: dp(5)
                        dash_offset: dp(5)

    ###################   ΔVθ   Line    ##########################
                    Line:
                        width: dp(1)
                        points: (float(root.xLText),float(root.yLText) + dp(20),float(root.xRText),float(root.yRText) + dp(20))

    ###################    ΔVθ  Dash lines    ##########################
                    Line:
                        width: dp(1)
                        points: (float(root.xLText),float(root.yLText),float(root.xLText),float(root.yLText)+dp(30))
                        dash_length: dp(5)
                        dash_offset: dp(5)
                    Line:
                        width: dp(1)
                        points: (float(root.xRText),float(root.yRText),float(root.xRText),float(root.yRText)+dp(30))
                        dash_length: dp(5)
                        dash_offset: dp(5)

    ################### Circles of stages numbers ###############################
                    Line:
                        width: dp(1.)
                        circle:
                            (float(root.xLText) - dp(15),float(root.yLText) + dp(17),dp(10))

                    Line:
                        width: dp(1.)
                        circle:
                            (float(root.xRText) + dp(15),float(root.yLText) + dp(17),dp(10))



                 ################################  Arrows   ##########################################
    ################### Base Velocity Arrows   ##########################
                    Triangle:
                        points:float(root.x0Text),float(root.y0Text),float(root.x0Text)+dp(25),float(root.y0Text)+dp(5),float(root.x0Text)+dp(25),float(root.y0Text)-dp(5)

                    Triangle:
                        points:float(root.x0Text),float(root.y0Text),float(root.xL1uText),float(root.yL1uText),float(root.xL1dText),float(root.yL1dText)

                    Triangle:
                        points:float(root.x0Text),float(root.y0Text),float(root.xL2uText),float(root.yL2uText),float(root.xL2dText),float(root.yL2dText)

                    Triangle:
                        points:float(root.x1Text),float(root.y1Text),float(root.xR1uText),float(root.yR1uText),float(root.xR1dText),float(root.yR1dText)

                    Triangle:
                        points:float(root.x1Text),float(root.y1Text),float(root.xR2uText),float(root.yR2uText),float(root.xR2dText),float(root.yR2dText)

    ##################  U Line Arrows  ####################
                    Triangle:
                        points:
                            float(root.x0Text),float(root.y0Text)-dp(20),float(root.x0Text)+dp(20),\
                            float(root.y0Text)-dp(20)+dp(3),float(root.x0Text)+dp(20),float(root.y0Text)-dp(20)-dp(3)
                    Triangle:
                        points:
                            float(root.x1Text),float(root.y1Text)-dp(20),float(root.x1Text)-dp(20),\
                            float(root.y1Text)-dp(20)+dp(3),float(root.x1Text)-dp(20),float(root.y1Text)-dp(20)-dp(3)

    ##################  ΔVθ Line Arrows  ####################
                    Triangle:
                        points:
                            (float(root.xLText),float(root.yLText) + dp(20),float(root.xLText)+ dp(20),float(root.yLText) + dp(20) + dp(3),\
                            float(root.xLText)+ dp(20),float(root.yLText) + dp(20) - dp(3)) if root.tc_nameText == 'Compressor' else\
                            (float(root.xRText),float(root.yRText) + dp(20),float(root.xRText)- dp(20),float(root.yRText) + dp(20) + dp(3),\
                            float(root.xRText)- dp(20),float(root.yRText) + dp(20) - dp(3))

    #####################  Vx Line Arrows  ####################
                    Triangle:
                        points:
                            (float(root.x1Text) + dp(20),float(root.y1Text),float(root.x1Text) + dp(20) + dp(3),\
                            float(root.y1Text)+dp(20),float(root.x1Text) + dp(20) - dp(3),float(root.y1Text)+dp(20))\
                            if float(root.xRText) < float(root.x1Text) else\
                            (float(root.xRText)+ dp(20),float(root.y1Text),float(root.xRText)+ dp(20) + dp(3),\
                            float(root.y1Text) + dp(20),float(root.xRText)+ dp(20) - dp(3),float(root.y1Text) + dp(20))

    ###################   Labels   ##########################
                Label:
                    pos: (float(root.ptn_xText),self.parent.y - self.height/2 + 0.05*self.height)
                    text: root.tc_nameText
                    color: 1,0,0,1

                Label:
                    text: 'U'
                    pos: dp(0),dp(-15)

                Label:
                    text: 'Vx'
                    pos:
                        (self.parent.x + float(root.UText)/2 + dp(35),\
                        self.parent.y +(-float(root.y0Text) + float(root.UText)*float(root.fText))/2)\
                        if (float(root.x1Text) - float(root.UText)*float(root.rnText) + float(root.UText)*float(root.pText)/2) < float(root.x1Text)\
                        else\
                        (self.parent.x + float(root.x1Text) - float(root.UText)*float(root.rnText)+\
                        float(root.UText)*float(root.pText)/2 - float(root.x0Text) - float(root.UText)/2 + dp(35),\
                        self.parent.y +(-float(root.y0Text) + float(root.UText)*float(root.fText))/2)

                Label:
                    text: '\u0394V\u03B8'
                    pos:
                        -float(root.UText)/2-float(root.x0Text)+float(root.xLText)+float(root.UText)*float(root.pText)/2,\
                        self.parent.y -float(root.y0Text)/2+float(root.UText)*float(root.fText)+ dp(25)

                Label:
                    text:'1' if root.tc_nameText == 'Compressor' else '3'
                    pos:
                        -float(root.UText)/2-float(root.x0Text)+float(root.xLText) - dp(15),\
                        self.parent.y -float(root.y0Text)/2+float(root.UText)*float(root.fText)+ dp(25) - dp(14)

                Label:
                    text:'2'
                    pos:
                        -float(root.UText)/2-float(root.x0Text)+float(root.xRText) + dp(15),\
                        self.parent.y -float(root.y0Text)/2+float(root.UText)*float(root.fText)+ dp(25) - dp(14)

            GridLayout:
                cols:2
                size_hint_y: 0.1
                canvas:
                    Color:
                        rgba: 0.6862,0.9333,0.9333,0.737
                    Rectangle:
                        pos: self.pos
                        size: self.size
                size_hint_y: 0.15
                BoxLayout:
                    size_hint_x:0.3
                    padding:dp(10)
                    spacing:dp(10)
                    Button:
                        size_hint:0.25,0.6
                        text:"Back"
                        on_release:
                            root.manager.current = "Main"
                            root.manager.transition.direction = "right"

                BoxLayout:
                    size_hint_x:0.7
